### ISSUE TITLE
[React Native] Damien Brugne

### ISSUE THREAD

**Issue by shprink** [GDGToulouse/meetup-cfp#1]
@dbrugne on peut en discuter ici ;)

**Comment by dbrugne** [comment]
@shprink discutons en alors :)

Quelle est la durée attendu ? Pour un public particulier ? Il y a déjà eu un présentation Native Script je crois, on peut voir la prés' quelque part ?

**Comment by shprink** [comment]
Hello!

La durée c'est a ta convenance mais max 45min. Le public sera aussi en fonction de ce que tu annoncera mais je pense que comme c'est une premiere, une introduction/ retour d'xp serait au top donc niveau `débutant`.

La presentation NativeScript n'a pas ete filme malheureusement, par contre les autres oui: https://www.youtube.com/user/ToulouseAUG

Un exemple de format court: https://youtu.be/_NxcNW_a7l4
format long: https://www.youtube.com/watch?v=IEwgKH26Xng

Des que tu aura un peu plus de certitude sur le contenu je t'invite a remplir ce template:

```
{ Veuillez remplir ce template pour nous aider à en savoir plus.
Pour le titre de l'issue, merci de respecter cette notation : [NOM DE VOTRE CONFERENCE] Prénom Nom }


## Le speaker
{ Votre prénom, nom, métier }

## Sujet de votre conférence
{ Identique à celle du titre }

## Description de votre conférence
{ La description de votre conférence en quelques lignes... }

## Informations diverses
* Thématique, Labels :
* Niveau de difficulté (débutant|avancé|confirmé) :
* Durée (max 45 min) : 
```

**Comment by shprink** [comment]
Hello Damien, ca avance ta reflexion sur la presentation? On est en train de book les sujets de Fevrier donc ca repousse a au moins fin mars pour le prochain meetup dispo.

**Comment by dbrugne** [comment]
En mars c'est mieux oui. Je cherche encore le bon curseur mais à titre de draft : 

## Le speaker
Damien Brugne, Javascript enthousiaste et consultant

## Sujet de votre conférence
React Native :  quoi, pourquoi, comment, pour qui ?

## Description de votre conférence
React Native a introduit un nouveau paradigme dans l'industrie du développement mobile. Qu'est ce que ça veut dire ? A quel point c'est vrai ? Quels apps sont concernés ?

* Quoi ?
  * Javascript (encore)
  * React.js
  * Imperative vs. Declarative UI
  * React Native
  * Du code !
* Pourquoi ?
  * Native or not native ?
  * "Using React is a Business Decision, Not a Technology Choice"
  * vs. Phonegap et Ionic ?
  * vs. Xamarin, Titanium ... ?
  * vs. Native script ?
  * vs. native ?
  * Un prototype en 2h, une soumission en 2 semaines
  * Réutilisation de code
* Pourquoi pas
  * Dans quels cas ne -surtout- pas utiliser React Native
  * Question de culture
* Comment ?
  * L'incommensurable indigence de Javascript ... c'est pas faux
  * Workflow
  * Les bons outils (Javascript fatigue fatigue)
  * Cohabitation
  * Performances
* Conclusion
  * Dois-je m'intéresser à React Native ?
  * Par où commencer ?
  * Bien finir.

## Informations diverses
* Thématique, Labels : Javascript, React.js, React Native, mobile
* Niveau de difficulté : débutant
* Durée : 45mn
```

**Comment by shprink** [comment]
Salut @dbrugne, tu as eu le temps d'avancer un peu les slides?

**Comment by shprink** [comment]
on a le 19 avril de confirmer avec la salle. TU me dit si c'est jouable de ton cote? Merci :)

**Comment by dbrugne** [comment]
19 avril ça me paraît bien.

**Comment by shprink** [comment]
Super, je vois avec notre deuxième speaker et reviens vers toi ASAP mais normalement ca devrait le faire :)

**Comment by shprink** [comment]
Hello, la date approche :) Tout va bien? Tu as besoin de quelque chose?
