### ISSUE TITLE
[Réalisation d'un WebService Rest en J2EE et son client sous Android] Anthony Monteiro

### ISSUE THREAD

**Issue by JulienDelRio** [GDGToulouse/meetup-cfp#11]
## Le speaker
Anthony Monteiro Formateur Android et Java

## Sujet de votre conférence
Réalisation d'un WebService Rest en J2EE et son client sous Android

## Description de votre conférence
Réalisation d'un WebService REST en Java JEE avec Jersey qui retournant du JSON ainsi qu'un client sous Android communiquant avec ce WebService.

## Informations diverses
* Thématique, Labels : Android, Mobile, Java JEE
* Niveau de difficulté (débutant|avancé|confirmé) : Confirmé
* Durée (max 45 min) :  1h

**Comment by ilaborie** [comment]
C'est quoi J2EE ?

**Comment by gdemiollis** [comment]
Est-ce qu'on peut avoir une précision sur le client Android?

**Comment by gdemiollis** [comment]
Je pense qu'on peut fermer cette issue.

**Comment by JulienDelRio** [comment]
Je crois qu'il n'est même plus à Toulouse.
