### ISSUE TITLE
[Introduction au développement Kotlin/Android] Arnaud Giuliani

### ISSUE THREAD

**Issue by arnaudgiuliani** [GDGToulouse/meetup-cfp#12]
## Le speaker
Arnaud Giuliani - Dev Mobile & Cloud @ ekito

## Sujet de votre conférence
Introduction au développement Kotlin/Android

## Description de votre conférence
Kotlin est un langage développé par Jetbrains. Sa version 1.0 (production ready) est sortie en début d'année 2016, faisant un certain buzz au sein de la communauté Android. Aujourd'hui en version 1.0.6, et bientôt 1.1, Kotlin continue de susciter un vif intérêt. 

A ekito, cela fait plus d'un an que nous travaillons sur ce langage et aujourd'hui, nous n'hésitons plus à lancer des applications en production avec Kotlin.

Cette session propose de découvrir ce langage, qui reprend certains aspects de groovy ou scala, et qui est très proche de swift dans la syntaxe et les concepts. Nous verrons comment Kotlin boost la productivité du développement d’applications Android et pourquoi vous ne pourrez plus vous en passer ;)

## Informations diverses
* Thématique, Labels : Langage de JVM, Développement Android 
* Niveau de difficulté : débutant
* Durée : ~45 min

A coupler avec le livecoding de Laurent Baresse #14

**Comment by davinkevin** [comment]
Quel est la part d'Android dans cette présentation ? Faut il obligatoirement avoir des notions dans ce domaine pour comprendre ?

**Comment by arnaudgiuliani** [comment]
La présentation est assez ouverte. Quelques focus sur Android, mais globalement largement compréhensible pour le développeur java (concepts assez généraux Java).
