### ISSUE TITLE
[Réaliser ses WebServices en Go] Patrice Trognon

### ISSUE THREAD

**Issue by ptro46** [GDGToulouse/meetup-cfp#17]
## Le speaker
Patrice Trognon, Développeur indépendant d'applications sur desktop ou mobile (iOS)

## Sujet de votre conférence
Réaliser ses WebServices en Go

## Description de votre conférence
Comment réaliser ses services web REST/JSON en Go, un exemple complet sera présenté avec gestion d'une base de données Postgres

## Informations diverses
* Thématique, Labels : Web Service en Go
* Niveau de difficulté (débutant|avancé|confirmé) : avancé, la connaissance du langage Go est un plus
* Durée (max 45 min) : 45 minutes
* Format (slides, live-coding, les deux): slides + demo

**Comment by aubm** [comment]
Salut @ptro46 ,

On essaye de monter un event Go pour début Décembre (le 6 ou 7).
Ta proposition de talk tient toujours ? Ca serait jouable pour toi à cette période ?

**Comment by ptro46** [comment]
bonjour,

Oui cela serait jouable, le format attendu c’est quoi ? (durée ? slide et / ou demo en live ? …. )

ca serait le 6 ou le 7 au soir ?

Pat

**Comment by aubm** [comment]
Cool !

Ca serait le soir oui.
Pour le format tu fais comme tu le sens, il faut juste que ça tienne en 45 minutes max.

Questions rapides :
- tu as déjà fait ce talk quelque part ?
- tu as déjà préparé des slides et/ou une demo que tu pourrais partager ?

**Comment by ptro46** [comment]
Le format me convient.

Ce Talk non je ne l’ai pas fait ailleurs puisque j’attendais une réponse de devfest pour le préparer.

Alors voici comment je vois la chose :
Je présente rapidement golang 
Réalisation d’un service rest GET
Un POST avec paramètre json en body et qui retourne un json
La connexion à la base.
Gestion de l’authentification.

Je livre la pres en pdf, et un exemple de code complet à récupérer sur github.

Je vais dev ça d’ici fin octobre.

Patrice

**Comment by ptro46** [comment]
Tu es sur le Slack de la communauté Toulouse ? 
Si oui quel pseudo ? J’y suis : ptro46, Ping moi on en parle dans la journée 

Patrice

**Comment by aubm** [comment]
Hello, on a pu réserver la salle pour le 6 décembre.
Toujours ok pour toi ?

**Comment by ptro46** [comment]
Yep ça roule toujours !


Patrice

**Comment by ptro46** [comment]
c’est de quelle heure a quelle heure ?

**Comment by aubm** [comment]
Répondu en MP
