### ISSUE TITLE
[Introduction à la programmation réactive avec Angular 2] Bruno Baia 

### ISSUE THREAD

**Issue by shprink** [GDGToulouse/meetup-cfp#2]
Debut du thread: https://github.com/AngularToulouse/meetups/issues/21

La programmation réactive ('Reactive Programming' en anglais) est un paradigme de programmation dont on entend parler de plus en plus aujourd'hui et qui devient indispensable de comprendre si on souhaite développer des applications Web modernes.
J'essaierai de démystifier tout ça avec des exemples concrets et son utilisation dans AngularJS 2.

Je vous propose une session d'1h sur le sujet, avec pas mal de démos.

@bbaia la conversation continue ici. Nous allons fermer le repo de AngularToulouse

**Comment by shprink** [comment]
@bbaia tu me dis des que tu as des news sur ta presentation :)

**Comment by shprink** [comment]
22 ou 23 Fevrier: tu es dispo?

**Comment by shprink** [comment]
le 23 serait mieux a priori

**Comment by bbaia** [comment]
OK pour le 23.

**Comment by bbaia** [comment]
Mise à jour de la description :

**Introduction à la programmation réactive avec Angular 2**
_Angular 2 adopte les Observables et la programmation Reactive. Apprenez ce qu'est un Observable et comment Angular 2 les utilise pour créer des applications avec une expérience utilisateur optimale._

**Comment by shprink** [comment]
salut @bbaia, tu as reussi a enlever des slides? Besoin de quoi que ce soit?

**Comment by bbaia** [comment]
C'est good.
Je vais enlever quelques slides et optimiser les démos pour tenir sur 45mn

**Comment by davinkevin** [comment]
Il faudrait que l'on fasse un test de partage d'écran avec Hangout Live pour éviter les mauvaises surprise demain... fait moi signe @bbaia dès que dispo 😄

**Comment by shprink** [comment]
@bbaia si tu peux nous donner le lien vers les slides ce serait cool. Encore un grand merci, c'etait super, les gens ont aimé!

**Comment by bbaia** [comment]
C'est par ici : https://slides.com/brunobaia/everything-is-a-stream
Et Merci à toi pour l'organisation. C'était nickel !

**Comment by shprink** [comment]
Video: https://youtu.be/U3jKJSjBbww
