### ISSUE TITLE
[WebAssembly] Nicolas Decoster

### ISSUE THREAD

**Issue by nnodot** [GDGToulouse/meetup-cfp#21]
## Le speaker
Nicolas Decoster, développeur et ingénieur scientifique @nnodot

## Sujet de votre conférence
WebAssembly

## Description de votre conférence

Petite conférence pour essayer de cerner ce qu'est cet OVNI dans l'univers des technos Web. Ce nouveau standard débarque dans les navigateurs et soulève pas mal de questions sur ses promesses (rapidité ! cible de compilation universelle !) et son positionnement par rapport aux autres technos, comme JavaScript que certains rêvent de voir disparaître (spoiler alert : non, WebAssembly n'a pas du tout vocation à remplacer JavaScript). Un peu d'histoire et de technique pour s'éclaircir les idées et pour voir comment on travaille avec cette techno.

## Informations diverses
* Thématique, Labels : WebAssembly, JavaScript
* Niveau de difficulté (débutant|avancé|confirmé) : débutant
* Durée (max 45 min) : 45 min
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y):

**Comment by davinkevin** [comment]
On a le droit de proposer moins de 45 minutes 😊

**Comment by nnodot** [comment]
En fait je ne sais pas encore ce que je vais dire, mais je pense qu'il peut y en avoir largement pour 45 min ! Par contre, pas de soucis, je peux aussi adapter la durée si besoin (disons, quand même pas en dessous de 20 min). S'il faut partager le temps avec d'autres speakers par exemple.

**Comment by maxdow** [comment]
Je met une option pour un toulousejs si ça vous va ? 
Éventuellement celui du 26 octobre ?

**Comment by nnodot** [comment]
Je présenterai déjà le sujet au DevFest un mois avant. Donc ça fait peut-être doublon ? Mais sinon, pas de problème pour le représenter à Toulouse JS.

**Comment by maxdow** [comment]
Cool :)

Ce n'est pas forcément contre indiqué, je ne suis pas certain que tous les devs js seront au Devfest ( enfin on le saura de toute façon, ils seront blacklistés :D )

**Comment by maxdow** [comment]
Je met une option dessus pour le 26 octobre. On pourrait faire une soirée : 
- présentation "nouveau" toulouseJS
- (grosse) intro veille ( vu que ça fait un moment qu'on a pas fait de meetup et qu'il y a des choses à dire ) 
- ton talk, en mode complet car il y aura le temps ( mieux vaut ça que vouloir à tout prix enchainer les sujets je pense )

**Comment by nnodot** [comment]
OK pour moi.

**Comment by shprink** [comment]
Video: https://youtu.be/YHQmic9EskE
