### ISSUE TITLE
[Comment séparer ses composants React ?] Julien Pradet

### ISSUE THREAD

**Issue by JulienPradet** [GDGToulouse/meetup-cfp#22]
## Le speaker
Julien Pradet, Développeur web @occitech

* Twitter handle: [@JulienPradet](https://twitter.com/JulienPradet)

## Sujet de votre conférence
Comment séparer ses composants React ?

## Description de votre conférence
Quand on parle React, on dit souvent qu'il faut faire une séparation entre les composants Dumbs et les composants Smart. Qu'est ce que ça veut dire&nbsp;? Est-ce que ça suffit pour réutiliser facilement nos composants&nbsp;? Est-ce qu'on ne risque pas de duppliquer le code propre à l'UI&nbsp;?

Pour répondre à ces questions, on essayera d'identifier les pièges à éviter afin d'en dégager quelques bonnes pratiques. Puis, on regardera comment React Storybook peut nous aider dans cette tâche.

## Informations diverses
* Thématique, Labels : React, Composants UI, React Storybook
* Niveau de difficulté : débutant
* Durée : 40min
* Format : slides
* Dispo ou indispo : avril

**Comment by shprink** [comment]
Hello, la date approche :) Tout va bien? Tu as besoin de quelque chose?
