### ISSUE TITLE
[Les tests E2E avec Protractor] Bruno Baia

### ISSUE THREAD

**Issue by bbaia** [GDGToulouse/meetup-cfp#23]
## Le speaker
Bruno Baia, Technical Lead indépendant

* Twitter handle: [@brbaia](https://twitter.com/brbaia)
* GitHub handle: [@bbaia](https://github.com/bbaia)

## Sujet de votre conférence
Les tests E2E avec Protractor

## Description de votre conférence
Après une introduction aux tests E2E (End to End), également appelés 'tests utilisateurs', je présenterais le Framework Selenium WebDriver sur lequel Protractor se base avant de se plonger dans l'écriture des tests E2E d'une application Web basée sur Angular... ou pas.

## Informations diverses
* Thématique, Labels : Angular, Tests
* Niveau de difficulté (débutant|avancé|confirmé) : débutant
* Durée (max 45 min) : 40min
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): A voir

**Comment by bbaia** [comment]
A coupler idéalement avec une session sur les tests unitaires avec Angular.

**Comment by shprink** [comment]
Hello,

on a deux sujets sur les tests avec Angular donc on peut commencer a parler de la date. https://github.com/GDGToulouse/meetup-cfp/milestone/9

Cette saison est fini avec le dernier meetup angular le 27 Juin. Apres il y a le devfest le 28 Septembre. Donc je dirais pas avant Octobre. 

Est ce que c'est une periode qui te conviendrais @bbaia ?

**Comment by bbaia** [comment]
Ca tombe bien, je me voyais pas faire ça de suite :)
Nickel pour octobre/novembre !

**Comment by maxdow** [comment]
Bonjour Bruno. Est ce que tu es toujours partant pour ce talk ?

**Comment by bbaia** [comment]
Salut Maxime,

Je ne l'utilise plus depuis un moment maintenant... 
Je préfère retirer ma proposition du coup.

Par contre, je vais créer un autre sujet sur Nest.js si ça vous dit. Y a pas mal de chose inspiré d'Angular.
