### ISSUE TITLE
[Java 9 vs. Swift 3] Didier Plaindoux

### ISSUE THREAD

**Issue by d-plaindoux** [GDGToulouse/meetup-cfp#24]
Swift est désormais open source ! "Google considérerait Swift comme un langage « de première classe » pour Android" pouvait-on lire en avril sur le réseau. Et enfin un portage Android du langage a été "merge" dans la base de code officielle de Swift.

Bon tout ceci est un bon prétexte pour apprendre ce langage et les possibilités qu'il peut nous apporter en terme de développement. Une comparaison avec Java 9 sera notamment proposée afin de montrer les similitudes et différences entre ces deux langages . 

## Le speaker
Didier Plaindoux

* Twitter handle: @dplaindoux

## Sujet de votre conférence
Java 9 vs. Swift 3

## Description de votre conférence
Cette conférence propose de faire une comparaison de ces deux langages notamment sur le domaine des paradigmes Objet et fonctionnel. 

Cette présentation est une version re-visitée de celle faite au DevFest et doit être présentée au prochain Voxxed Luxembourg fin juin prochain.

## Informations diverses
* Thématique, Labels : OOP, FP, Expressivité
* Niveau de difficulté (débutant|avancé|confirmé) : avancé
* Durée (max 45 min) : 45min
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): avant le 15 juin

**Comment by shprink** [comment]
Ca fait plaisir!

**Comment by gdemiollis** [comment]
On peut fermer vu qu'on en est à Swift 5.1

**Comment by d-plaindoux** [comment]
En même temps si vous êtes lents je n'y suis pour rien 😁

**Comment by d-plaindoux** [comment]
On peut fermer donc.
