### ISSUE TITLE
[Lazy Loading en Just Angular : Aïe ? ] Igor Laborie

### ISSUE THREAD

**Issue by ilaborie** [GDGToulouse/meetup-cfp#27]
## Le speaker
Igor Laborie, 'Expert' Web & Java chez MonkeyPatch

* Twitter handle: @ilaborie

## Sujet de votre conférence
Lazy Loading en Just Angular : Aïe ?

## Description de votre conférence

Live-coding pour expliquer comment on peut faire du lazy-loading dans Angular.
Voir par exemple http://www.monkeypatch.io/2017/03/07/ngVikings.html#part-i---lazy-loading

## Informations diverses
* Thématique, Labels : Angular
* Niveau de difficulté (débutant|avancé|confirmé) : débutant/avancé
* Durée (max 45 min) :  30 min
* Format (slides, live-coding, les deux): live-coding
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): Pas avant Juin, il me faudra un peu de préparation (disons être prévenu 1 mois avant)

**Comment by shprink** [comment]
Hello on aurait une possibilite de faire un event le 29 juin pour clore la saison des meetups GDG. Phillippe est en train de voir pour venir. Tu serais dispo?

**Comment by ilaborie** [comment]
OK pour moi

2017-04-28 12:39 GMT+02:00 Julien Renaux <notifications@github.com>:

**Comment by ilaborie** [comment]
Ooops !

J'ai répondu un peu vite, mais je suis pas dispo le 29 Juin, on a le Monkey-Council (aka AG de MonkeyPatch) donc je ne peux pas cette soirée là.
Par contre je suis dispo les autres jours de la semaine du 26 Juin, voir la semaine précédente.

Désolé,

Igor

**Comment by shprink** [comment]
le 28 c'est good?

**Comment by ilaborie** [comment]
Je confirme que c'est ok


Le mar. 2 mai 2017 à 10:43, Julien Renaux <notifications@github.com> a
écrit :

**Comment by shprink** [comment]
hello, la salle peut pas, tout le monde est ok pour le 27. dis moi si tu peux au plus vite merci :)

**Comment by choucry13** [comment]
@shprink moi ca me va :-)
