### ISSUE TITLE
[Unity3D] Benjamin Gimet

### ISSUE THREAD

**Issue by Bgimet** [GDGToulouse/meetup-cfp#31]
## Le speaker
Benjamin Gimet, gérant de la société Octotek-Studios
Développeur Unity3D et mobile
https://twitter.com/GimetBenjamin

## Sujet de votre conférence
Unity3D

## Description de votre conférence
L'idée est de faire partager mes quelques années d'expérience sur le moteur de jeu Unity3D, en abordant des thèmes autres que le jeu-vidéo. J'utilise ce moteur professionnellement depuis des années pour des projets en aéronautique, dans le médical, la défense, l'immobilier en faisant de la VR, de la RA, des applis mobiles ou desktop.

## Informations diverses
* Thématique, Labels : Unity3D, C#, VR, RA, Mobile
* Niveau de difficulté (débutant|avancé|confirmé) : Tout niveau
* Durée (max 45 min) : 45min max
* Format (slides, live-coding, les deux): Slides + démos 
* Dispo : Le mois d'Octobre serait le plus approprié pour moi, mais je peux m'arranger si besoin

**Comment by shprink** [comment]
Nice! Tu connais un autre speaker de qualité qui voudrait parler de Unity par hasard? Qu'on fasse une soiree a theme si possible.

**Comment by Bgimet** [comment]
Yes je pense que mon associé sera partant !

**Comment by shprink** [comment]
il faudrait que ce soit un sujet different mais toujours sur Unity si possible.

**Comment by Bgimet** [comment]
Ok je vais trouver ça ;)

**Comment by shprink** [comment]
Le meetup vient d'etre annonce a nos membres: https://www.meetup.com/GDG-Toulouse/events/245030403/

**Comment by shprink** [comment]
Merci pour tout Benjamin, 

Est ce que tu avais des slides ou autres a partager aux gens? Si oui tu peux commenter sur l'event directement: https://www.meetup.com/GDG-Toulouse/events/245030403/
