### ISSUE TITLE
Programmation fonctionnelle en JavaScript : 🦄 ou 💩 ?

### ISSUE THREAD

**Issue by ilaborie** [GDGToulouse/meetup-cfp#33]
{ Veuillez remplir ce template pour nous aider à en savoir plus.
Pour le titre de l'issue, merci de respecter cette notation : [NOM DE VOTRE CONFERENCE] Prénom Nom }

## Le speaker
Igor Laborie, expert Java, Web, Trolls

* Twitter handle: @ilaborie

## Sujet de votre conférence
Programmation fonctionnelle en JavaScript : 🦄 ou 💩 ?

## Description de votre conférence
Qu'est que la programmation fonctionnelle ? un langage fonctionnel ?
Comment peut-on programmer en fonctionnel avec JavaScript / TypeScript ?
Bilan: 🦄 ou 💩 

## Informations diverses
* Thématique, Labels : programmation fonctionnelle
* Niveau de difficulté (débutant|avancé|confirmé) : débutant
* Durée (max 45 min) : 45min (disons plutot 1h)
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): >= 2018, me valider au moins 1 mois à l'avance

**Comment by shprink** [comment]
Il me tarde 😍

**Comment by maxdow** [comment]
Ca va être énorme, j’espère qu'il y aura de la pyrotechnie

**Comment by ilaborie** [comment]
Compte tenu des conférences que je pourrai faire cette année, il y a une fenêtre de tir pour faire ça fin févirer/début mars, sinon se sera plutôt fin mai/juin

**Comment by shprink** [comment]
Allez c'est parti pour le 17 Mai!!!
Merci Igor <3

**Comment by shprink** [comment]
Hello,

On a des goodies Google Io a faire gagner. Est ce que vous pouvez reflechir à 5 questions chacun sur votre sujet? 

merci à Jeudi!
