### ISSUE TITLE
[Faire du Redux avec Angular et ngrx v4] Bruno Baia

### ISSUE THREAD

**Issue by bbaia** [GDGToulouse/meetup-cfp#37]
## Le speaker
Bruno Baia, Lead Software Engineer chez [Delair](http://delair.aero)

* Twitter handle: [@brbaia](https://twitter.com/brbaia)
* GitHub handle: [@bbaia](https://github.com/bbaia)

## Sujet de votre conférence
Faire du Redux avec Angular et ngrx v4

## Description de votre conférence
Après une présentation du Framework **ngrx**, l'équivalent de **Redux** pour **Angular**, nous verrons en quoi il est intéressant d'utiliser ce type de pattern de développement sur des applications qui deviennent de plus en plus élaborées et complexes à maintenir.

## Informations diverses
* Thématique, Labels : Angular, Redux, State management
* Niveau de difficulté (débutant|avancé|confirmé) : confirmé
* Durée (max 45 min) : 30mn
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): ASAP

**Comment by shprink** [comment]
Good job, on attend le retour du MobX et on organise ca pour janvier ou fevrier (on est book jusqu'a decembre inclus)

**Comment by davinkevin** [comment]
Je devais en faire une en interne de présentation ng-rx... donc je leur dirai de venir au GDG 👍

**Comment by shprink** [comment]
@bbaia j'ai besoin de ta reponse (c.f Slack en PM)
