### ISSUE TITLE
[Ce que j'aurais aimé savoir en me lançant dans la domotique] Michaël Bitard

### ISSUE THREAD

**Issue by MichaelBitard** [GDGToulouse/meetup-cfp#38]
## Le speaker
Michaël Bitard, Développeur indépendant

* Twitter handle: @BitardMichael

## Sujet de votre conférence
Ce que j'aurais aimé savoir en me lançant dans la domotique

## Description de votre conférence
Avec l'essor de l'IOT, de plus en plus de personnes sont tentées par la domotique. Les grandes enseignes s'y mettent, avec plus ou moins de succès. Notre métier nous permet une plus grand liberté dans ce domaine, encore faut-il ne pas se perdre dans ce qui existe.
Je vous propose un tour d'horizon (non exhaustif) de ce qui se fait, les solutions que j'ai choisies pour mon domicile ainsi que des pistes pour ceux qui souhaitent se lancer.
Attention, il y'aura du troll.

## Informations diverses
* Thématique, Labels : domotique, RF, IOT, arduino, diy, wifi
* Niveau de difficulté (débutant|avancé|confirmé) : débutant/avancé
* Durée (max 45 min) : < 45 min
* Format (slides, live-coding, les deux): slides/démos 
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y):

**Comment by davinkevin** [comment]
Bonjour, 

Pour la captation, nous allons utiliser Hangout Live, donc il faudra que vous soyez équipé d'un compte Google et que vous ayez accès à Google Hangout. Ajoutez moi dans vos contact (davin point kevin sur g mail point com ) et je vous enverrai le lien à rejoindre la session de ce soir. 

Si vous avez des questions, n'hésitez pas ;)

**Comment by MichaelBitard** [comment]
[https://t.co/30IJ7Ueg78(slides)
