### ISSUE TITLE
[WebGPU et un apercu du developement de standards Web] Corentin Wallez

### ISSUE THREAD

**Issue by Kangz** [GDGToulouse/meetup-cfp#39]
cc @swallez

## Le speaker

Corentin Wallez, ingenieur logiciel sur Chromium a Google Montreal, co-chair du groupe W3C "WebGPU".

 - Twitter handle: [@DaKangz](https://twitter.com/DaKangz)
 - Experience en tant que Speaker: avancé.

## Sujet de votre conférence

WebGPU et un apercu du developement de standards Web

## Description de votre conférence

Les cartes graphiques (GPUs) sont particulierement efficaces pour l'execution d'algorithmes tres paralleles comme le traitement d'image, le machine learning et le rendu 3D. Les GPUs sont exposees de facon limitee et moyennement efficace sur le Web avec la technologie WebGL. WebGPU est une technologie en cours de standardization qui succedera a WebGL et permettra d'acceder a plus de fonctionnalites des GPUs.

La conference sera essentiellement en deux parties. La premiere presentera les GPUs, WebGL et ses defauts et comment WebGPU les corrige. La deuxieme essayera de lever le voile sur le processus de creation d'APIs Web, les conflits et collaborations entre developpeurs de navigateurs, les contraintes propres au Web, bref, comment on fait le boudin.

## Informations diverses

 - Thématique, Labels : GPU, WebGL, WebGPU, processus de standardization d'API Webs
 - Niveau de difficulté (débutant|avancé|confirmé) : Debutant
 - Durée (max 45 min) : 45m
 - Format: slides + demo d'un prototype.
 - Dispo ou indispo : dispo de 2018-01-02 a 2018-01-07, bornes incluses.

**Comment by ltearno** [comment]
+1

**Comment by NotBad4U** [comment]
+1000

**Comment by shprink** [comment]
Good news, nous pouvons le faire le 4 Janvier chez HarryCow! C'est bon pour toi @Kangz ?

**Comment by Kangz** [comment]
C'est parfait!

**Comment by shprink** [comment]
Le meetup vient d'etre annonce a nos membres: https://www.meetup.com/GDG-Toulouse/events/245030403/

**Comment by shprink** [comment]
@Kangz si tu as des questions n'hesites pas a nous contacter ici ou si tu veux chat tu peux m'ajouter sur twitter @julienrenaux et/ou venir sur le Slack des communautes toulousaines: http://communautes-toulouse.herokuapp.com/

**Comment by Kangz** [comment]
Merci, je te contacterai si j'ai des questions auquel @swallez ne sait pas repondre ;-)

**Comment by shprink** [comment]
Tu viens plus, un probleme?

![image](https://user-images.githubusercontent.com/1388706/34489980-8b64199e-efde-11e7-8b53-9517a423ea3f.png)

**Comment by swallez** [comment]
@shprink No problem. C'est juste moi qui lui ai dit que comme il est speaker, c'était pas utile de prendre une place de spectateur !

**Comment by shprink** [comment]
😌

**Comment by Kangz** [comment]
Whoops, je pensais pas que ca allait apparaitre sur l'UI de meetup. Sinon il faut venir un peu plus tot pour faire un A/V check?

**Comment by MaximePawlakFr** [comment]
Si possible. Mais surtout vérifier que tu arrives à partager ton écran avec Hangout. Si t'as un email pour que je t'invite au hangout de demain ,c 'est encore mieux.
Merci d'avance

**Comment by shprink** [comment]
Viens autour de 18h, on commence a 19h sharp

**Comment by Kangz** [comment]
Voici quelques liens:

 - [les slides](https://docs.google.com/presentation/d/1l1rTCtKHowIEhwzA4l1uEq2_JtiKolApTOgA0ebRJIM)
 - [une video du "Epic Zen Garden" en WebGL](https://www.youtube.com/watch?v=TwuIRcpeUWE)
 - [une video de la demo du prototype de Google](https://youtu.be/ThlZ5K4hJvo?t=11) (la deuxieme demo de la video)

**Comment by davinkevin** [comment]
Merci ! 😉

Le jeu. 4 janv. 2018 à 20:02, Corentin Wallez <notifications@github.com> a
écrit :

**Comment by Kangz** [comment]
Ah on m'avait aussi demande un lien vers le code JS de la demo, [le voici](https://github.com/Kangz/nxt-chromium/blob/master/_NXT_demos/webglnext-boids/index.html).

**Comment by shprink** [comment]
Merci j'ai partage sur la page meetup. 
Encore merci pour ta presentation, tu reviens quand tu veux :)

**Comment by davinkevin** [comment]
Vidéo publiée : https://youtu.be/rkVnBBJy5c4
