### ISSUE TITLE
[Actions on Google] Marc Plano-Lesay

### ISSUE THREAD

**Issue by Kernald** [GDGToulouse/meetup-cfp#40]
## Le speaker
Marc Plano-Lesay, développeur Android chez Viseo

* Twitter handle: @marcpl31
* Experience en tant que Speaker: débutant

## Sujet de votre conférence
Actions on Google

## Description de votre conférence
Le Google Home est disponible en France, et commence à devenir un concurrent intéressant à Alexa dans la langue de Molière. Faisons donc un petit tour de ce qu'il permet, notamment via le SDK Actions on Google, et sa fonctionnalité Smart Home.

## Informations diverses
* Thématique, Labels : Actions on Google, domotique, Google Assistant, Smart Home
* Niveau de difficulté (débutant|avancé|confirmé) : débutant
* Durée (max 45 min) : 45 minutes
* Format (slides, live-coding, les deux): slides + démo
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y):

**Comment by davinkevin** [comment]
Bonjour, 

Pour la captation, nous allons utiliser Hangout Live, donc il faudra que vous soyez équipé d'un compte Google et que vous ayez accès à Google Hangout. Ajoutez moi dans vos contact (davin point kevin sur g mail point com ) et je vous enverrai le lien à rejoindre la session de ce soir. 

Si vous avez des questions, n'hésitez pas ;)
