### ISSUE TITLE
[Introduction à RxJava] David Blanc

### ISSUE THREAD

**Issue by speekha** [GDGToulouse/meetup-cfp#41]
## Le speaker
David Blanc, développeur Android chez i-BP

* Twitter handle: @speekha
* Experience en tant que Speaker: débutant

## Sujet de votre conférence
Introduction à RxJava

## Description de votre conférence
Les applications mobiles combinent beaucoup de sources de données ou d'événements asynchrones auxquels il faut répondre. Si beaucoup de façons de répondre à cette contrainte existent sous Android (AsyncTasks, services, event bus, etc.), l'utilisation de RxJava a de plus en plus le vent en poupe ces derniers temps. Nous allons donc nous familiariser avec cette librairie pour voir son intérêt dans une application mobile.

## Informations diverses
* Thématique, Labels : Rx, Kotlin, Android
* Niveau de difficulté (débutant|avancé|confirmé) : débutant
* Durée (max 45 min) : 45 minutes
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): à partir de janvier

**Comment by shprink** [comment]
Merci pour cette proposition. Nous reviendrons vers toi quand un event sur le sujet sera en preparation!

**Comment by EmmanuelVinas** [comment]
Salut, pour fin janvier/début février ca serait bon pour toi ?

**Comment by speekha** [comment]
Bonjour.

Oui ça a l'air pas mal.

David


Le 22 nov. 2017 16:30, "Emmanuel Vinas" <notifications@github.com> a écrit :

Salut, pour fin janvier/début février ca serait bon pour toi ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GDGToulouse/meetup-cfp/issues/41#issuecomment-346384688>,
or mute the thread

**Comment by EmmanuelVinas** [comment]
C'est prévu pour le 18 Janvier. C'est bon ?

**Comment by EmmanuelVinas** [comment]
Meetup annoncé : https://www.meetup.com/fr-FR/GDG-Toulouse/events/245524794

**Comment by EmmanuelVinas** [comment]
Salut, Dans les temps pour la préparation de la conf ? 
une préférence de passer en premier ou second ?

**Comment by speekha** [comment]
Pas de souci de mon côté, et pas de préférence pour passer en premier ou en
second. Sinon, vu qu'ibp est sponsor, ça sera possible de prendre genre 5
minutes au début pour présenter ibp ?

Le 9 janv. 2018 5:31 PM, "Emmanuel Vinas" <notifications@github.com> a
écrit :

**Comment by EmmanuelVinas** [comment]
Pas de problème pour prendre 5 minutes pour présenter iBP, le sponsoring est aussi fait pour ca 👍

**Comment by EmmanuelVinas** [comment]
Lien de la vidéo : https://www.youtube.com/watch?v=eJBF-pFWWyY
