### ISSUE TITLE
[Traitement d'image simple et rapide avec Renderscript sur Android] Quentin Menini

### ISSUE THREAD

**Issue by qhutch** [GDGToulouse/meetup-cfp#42]
## Le speaker
Quentin Menini, développeur Android chez Pictarine

* Twitter handle: [@QMenini](https://twitter.com/QMenini)
* Experience en tant que Speaker: débutant

## Sujet de votre conférence
Traitement d'image simple et rapide avec Renderscript sur Android

## Description de votre conférence
Vous avez toujours voulu faire du traitement d'image sur Android? Blur sur les images, filtres à la snapchat, édition à la instagram... Les performances sont un frein pour vous?
Grâce à ma méthode, vous allez apprendre comment simplement utiliser le calcul parallèle pour enfin éditer des images à la vitesse de l'éclair. En m'appuyant sur des exemples concrets, comme l'ajout du blur sur une image compromettante, ou l'amélioration de la luminosité d'une image en analysant son contenu, je vous montrerai la simplicité de cet outil.

## Informations diverses
* Thématique, Labels : Renderscript, traitement d'images, Android
* Niveau de difficulté (débutant|avancé|confirmé) : avancé
* Durée (max 45 min) : 20 minutes
* Format (slides, live-coding, les deux): slides
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): à partir de février

**Comment by EmmanuelVinas** [comment]
Salut, pour fin janvier/début février ca serait bon pour toi ?

**Comment by qhutch** [comment]
Oui parfait

**Comment by EmmanuelVinas** [comment]
C'est prévu pour le 18 Janvier. C'est bon ?

**Comment by qhutch** [comment]
Nickel

**Comment by EmmanuelVinas** [comment]
Meetup annoncé : https://www.meetup.com/fr-FR/GDG-Toulouse/events/245524794

**Comment by EmmanuelVinas** [comment]
Salut, Dans les temps pour la préparation de la conf ? 
une préférence de passer en premier ou second ?

**Comment by qhutch** [comment]
Salut,
Je suis dans les temps, les slides don't terminées.
Je préférerais passer en premier si c'est possible

**Comment by speekha** [comment]
Pas de souci pour moi, je te laisse passer d'abord, je les endors ensuite. :)

**Comment by EmmanuelVinas** [comment]
Lien de la vidéo : https://www.youtube.com/watch?v=3uig28KyBFw
