### ISSUE TITLE
[Kotlin par l'exemple] Emmanuel Vinas & Igor Laborie

### ISSUE THREAD

**Issue by EmmanuelVinas** [GDGToulouse/meetup-cfp#43]
## Les speaker
Emmanuel Vinas: IT developper
Igor Laborie : 'Expert' Web & Java chez MonkeyPatch

* Twitter handle: @EmmanuelVinas @ilaborie
* Experience en tant que Speaker: avancé

https://cfp.devoxx.ma/2017/talk/GWR-8354

## Sujet de votre conférence
Kotlin par l'exemple

## Description de votre conférence
En annoncant le support officiel de Kotlin pour Android lors de la dernier Google I/O, Google a donné un énorme élan à ce superbe langage. Ce n'est pas si surprenant, car en s'inspirant du meilleur de Scala, Groovy, Go, ... et en ciblant la meilleure VM disponible, Kotlin part avec beaucoup d'avantages. En prenant le temps avant de sortir la v1.0, beaucoup de pièges classiques ont étés évités. Dès aujourd'hui le langage profite d'un outillage mature, tout en étant très abordable pour les développeurs. Au travers d'exemples concrets en environnement multiplatforme, venez découvrir les éléments du langages qui ont su nous séduire.

## Informations diverses
* Thématique, Labels : Android, Web, Kotlin
* Niveau de difficulté : débutant/avancé
* Durée (max 45 min) : 45 minutes
* Format (slides, live-coding, les deux): les deux
* Dispo ou indispo (après mars, dès que possible, pas entre X et Y): dès que possible, en 2018

**Comment by maxdow** [comment]
Js dans les labels ?

**Comment by EmmanuelVinas** [comment]
https://kotlinlang.org/docs/tutorials/javascript/kotlin-to-javascript/kotlin-to-javascript.html
