### ISSUE TITLE
[Devtools yourself] Paul Musso 

### ISSUE THREAD

**Issue by popul** [GDGToulouse/meetup-cfp#47]
Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you

* Name: Paul Musso
* Link to profile picture : https://avatars2.githubusercontent.com/u/2310967?s=460&v=4
* Job title: Développeur Javascript
* Company: L'atelier des logiciels
* Twitter handle: paulmuss0
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
- https://paulmusso.github.io/rex-tests-webcom
- https://popul.github.io/why-testing-slides
- https://paulmusso.github.io/webpack-slides ([video](https://youtu.be/UrVQDZVe0xE))
- http://paulmusso.github.io/eagle-slides
---

## Description of your talk

Comment les devtools peuvent-ils vous aider dans votre quotidien de développeur web ?

Nous aborderons les 3 problématiques suivantes :
- **Debugging de vos applications** (Différentes façons de définir des breakpoints, modification du code dans les devtools et récupération des modifications, debugging Node.JS)
- **Optimisation de votre code Javascript** (Profiling JS, onglet Performances et l'API console)
- **Tests de vos applications web** (Puppeteer, devtool protocol, lighthouse)

Nous verrons ensemble différentes approches et solutions qu'apportent les devtools, avec le plus souvent des démonstrations live et des tips, de manière très fun !

La présentation sera abordable pour tous les développeurs web.

Slides: https://popul.github.io/slides-chrome-devtools
Demo: https://github.com/atelier-des-logiciels/demo-chrome-devtools

---

## Miscs

* Tags (e.g: angular, android, web, iot) : web, javascript, devtools
* Talk level :
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Length (max 45 min) : 30 min
* Format:
    - [x] Slides
    - [x] Live coding
    - [ ] Video
    - [ ] Sound
* Availability: January 2018 !

**Comment by shprink** [comment]
😍🔥

**Comment by shprink** [comment]
Hello Paul,

Maxime a du te proposer le 17 Mai, est-ce toujours bon pour toi?

Le deuxieme talk sera par @ilaborie : https://github.com/GDGToulouse/meetup-cfp/issues/33

SI c'est ok, je commence la com.

Merci

**Comment by popul** [comment]
Hello Julien,

Oui je suis partant pour le 17 mai.
Tu peux y aller :)

Paul

**Comment by shprink** [comment]
Great! merci

**Comment by maxdow** [comment]
@ilaborie tu arrivera à tenir sur le format 40min ?

**Comment by ilaborie** [comment]
Non, 1h avec les questions

Le mar. 17 avr. 2018 à 11:23, Maxime Warnier <notifications@github.com> a
écrit :

**Comment by maxdow** [comment]
@popul tu avais prévu 30 min, est ce que c'est tjrs ok ? 

L'idéal serait de ne pas trop dépasser 1h30 donc si on reste sur ces timings ca ira bien

**Comment by popul** [comment]
Je pensais garder un peu de temps pour les questions/réponses après les 30 minutes de la présentation, 5 minutes disons.

**Comment by maxdow** [comment]
ok pas de pb si on fait 1h40 c'est cool aussi ;)

**Comment by shprink** [comment]
Hello,

On a des goodies Google Io a faire gagner. Est ce que vous pouvez reflechir à 5 questions chacun sur votre sujet? 

merci à Jeudi!

**Comment by popul** [comment]
Ca marche !
