### ISSUE TITLE
Koin in Action

### ISSUE THREAD

**Issue by arnaudgiuliani** [GDGToulouse/meetup-cfp#49]
Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

## About you

* Name: Arnaud Giuliani
* Link to profile picture (best quality you have): https://www.ekito.fr/img/team/aguiliani.jpg
* Job title: Développeur sénior & Architecte
* Company: ekito
* Twitter handle: @arnogiu
* Experience as a speaker:
    - [ ] beginner
    - [X] advanced
    - [ ] expert
* Links to your previous events, videos etc. :

Mes présentations :  https://medium.com/@giuliani.arnaud/presentations-6b91f53899ac
* DevoxxFr 2016 / 2017
* AndroidMakers 2017
* DevFest 2016 2017
* GDG Toulouse (autres Android User Group) 2017
* et différents rdv techniques toulousains

---

Koin (https://insert-koin.io/) est nouveau framework d'injection de dépendances pour tous les développeurs Kotlin (mobile, web, ...)

* Prise en main en 5 minutes chrono 
* DSL First !
* Pas d'introspection, de proxy, ni de génération de code

Déclarez vos dépendances, lancez Koin et injectez dans votre application.

Ce talk commencera par la présentation du framework et de son DSL suivi d'une séance de live-coding dans différents contextes (Android, SparkJava ...).

---

## Miscs

* co présenteur: Laurent Baresse

* Tags (e.g: angular, android, web, iot) : kotlin, android, web
* Talk level :
    - [X] beginner
    - [] advanced
    - [ ] expert
* Length (max 45 min) : 45 min
* Format:
    - [X] Slides
    - [X] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): Mars, ou à partir de Mai

**Comment by gdemiollis** [comment]
À fermer!

**Comment by arnaudgiuliani** [comment]
of course 👍
