### ISSUE TITLE
[Les notifications fingers in the nose avec Firebase] Maxime Pawlak

### ISSUE THREAD

**Issue by MaximePawlakFr** [GDGToulouse/meetup-cfp#5]
## Prenom, Nom, Métier: 
Maxime Pawlak, développeur web et compère, j'entreprend qq projets farfelus et je fais de la formation à Simplon.co

## Sujet de votre conférence: 
Les notifications fingers in the nose avec Firebase 

## Description de votre conférence: 
Avec Firebase, envoyer des notifications est un jeu d'enfant. Que ce soit pour du web ou du natif, nous aborderons les notions essentielles pour bien démarrer avec Firebase Cloud Messaging (la techno d'envoi de notification de Firebase).  

L'objectif est de vous montrer que vous pouvez rapidement proposer un service de notification à vos utilisateurs, peu importe la plateforme qu'ils utilisent.

Nous mettrons en place un service afin d'envoyer nos notifications pour des navigateurs web, pour Android, iOS et Ionic.

* Thématique: Firebase, notifications, FCM, 
* Niveau de difficulté (débutant|avancé|confirmé): débutant
* Durée (max 45 min): 45min

**Comment by EmmanuelVinas** [comment]
Dispo pour Novembre ?

**Comment by MaximePawlakFr** [comment]
Nope
