### ISSUE TITLE
[VueJS et son écosystème] Mathieu Dartigues

### ISSUE THREAD

**Issue by mdartic** [GDGToulouse/meetup-cfp#55]
{ Please fill in this template to help us have a better understanding about you and your talk. Use this pattern for the issue title: [talk title] Firstname Lastname }

Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you

* Name: Mathieu Dartigues
* Link to profile picture (best quality you have): https://makina-corpus.com/portal_memberdata/portraits/mda
* Job title: Développeur Web
* Company: Makina Corpus
* Twitter handle: mdartic
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
aucun
---

## Description of your talk (200 characters at least)

VueJS, un framework qui gagne tous les jours en popularité. 
Mais, n'est il pas juste ce monstre du Loch Ness... beaucoup en parlent, mais peu l'ont réellement vu ?
Ou pratiqué, dans notre cas. 
Mature au point d'en faire de vrais projets ? 
Facile à prendre en main comme le voudrait la légende ?
Quel recul a t'on réellement sur son utilisation sur la banlieue toulousaine ?

L'idée de ce talk est de proposer une vision d'ensemble de ce que propose la librairie VueJS, et son écosystème. 
Puis, à travers plusieurs projets de différents intervenants, essayer d'obtenir du feedback sur son utilisation en entreprise, avec des projets mis en production et utilisés / maintenus au quotidien.

---

## Miscs

* Tags (e.g: angular, android, web, iot) : vuejs, javascript
* Talk level :
    - [x] beginner
    - [x] advanced
    - [ ] expert
* Length (max 45 min) : 45mn me paraît un peu court, mais j'imagine plutôt 30mn pour la prés de l'écosystème et 10mn par feedback de projet. Avec 3 projets, on atteindrait 1h. A discuter.
* Format:
    - [x] Slides
    - [x] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): à définir, car j'imagine ne pas être seul sur ce format.

**Comment by maxdow** [comment]
Merci pour la proposition.

On peut faire carrément une soirée VueJs . 

Il y a un talk qui attend depuis très longtemps sur les devtools mais j'ai peur qu'on ne puisse pas assez développer Vue si on essaye de caser les 2 et inversement, que le talk devtools ne soit pas assez mis en avant.

Donc on peut partir sur 1h 1h30 de Vue.

30min de prez c'est bien pour faire le tour puis 15/20min par feedback ?

**Comment by mdartic** [comment]
Oui 30mn je pense que c'est bien, et qu'il faut se maintenir car au delà les gens risquent de se lasser.

Pour le feedback, ok aussi, je me rends pas bien compte du temps qu'il faut pour un bilan de projet en rapport à la stack utilisée. Il faudra sûrement structurer cette partie de manière à ce que chaque feedback ait une trame partagée.

Les formats ToulouseJS durent combien de temps habituellement ? 1h ? 2h ? 

Je reste de ton avis sur le fait de concentrer la soirée sur VueJS, car je l'espère, il devrait y avoir des questions, et ça débordera sûrement... du coup, ça risque de pénaliser le 2ème qui passe : soit les devtools, soit vuejs.

**Comment by maxdow** [comment]
En général c'est 2 talks de 40min + petite intro. L'important c'est de ne pas faire trop long non plus. 
1h30 tout compris c'est bien, et s'il y a plein de questions et qu'on a commencé à l'heure alors on fera éventuellement plus..

**Comment by gdemiollis** [comment]
Est-ce que tu aurais une partie architecture par hasard? Genre comment découper / organiser les fichiers pour ne pas qu'ils soient trop gros? On a un peu cette problématique à mon boulot en ce moment.

**Comment by ogadaki** [comment]
Si ça vous dit je pourrai faire un retour sur mon utilisation en temps que grand débutant (j'ai commencé il y a une semaine...). Le type d'application est la mise en œuvre de petites applis développées rapidement pour de la visu et manipulation de données (images en particulier). C'est un use cas différent des gros sites web en prod mais ça me semble complémentaire et ça montre le côté simple et accessible de Vue.js.

**Comment by mdartic** [comment]
@gdemiollis ok, on peut ajouter cette problématique de l'appli qui grossit, et qu'on doit penser correctement en terme d'archi.
@nnodot why not, la partie feedback peut brasser plusieurs typo de projets, et le 'petit' projet, sans que ce soit péjoratif, fait partie des typo de projets que l'on peut faire avec VueJS. C'est une bonne idée.

**Comment by Tactless7** [comment]
Côté Schoolmouv on a notre produit principal qui tourne en prod sous vue (+ de 600 000 users) , et on a aussi une appli interne en vue packagée avec electron.

**Comment by maxdow** [comment]
2 choses pour driver l'organisation : 
pour l'instant, qui est ok pour présenter qq chose ? 

@mdartic présentation technique en collaboration avec @Tactless7 
@Tactless7 retour XP Schoolmouv
@nnodot retour sur ton projet/experience "débutant"
? 
( c'est juste une proposition compte tenu des échanges, vous êtes absolument libre de faire comme bon vous semble )


Concernant les créneaux, il y aurait des possibilités en mai . 
Est ce que vous avez des contraintes ?

**Comment by mdartic** [comment]
Ta proposition me va, je peux aussi présenter un projet pro, de taille bien plus modérée que SchoolMouv, mais qui a pour intérêt d'être en prod°.
Concernant les contraintes de Mai, je suis pas dispo la semaine du 7 Mai. 
Je privilégie les lundi / jeudi, mais je crois que ToulouseJS c'est le Jeudi ?

**Comment by ogadaki** [comment]
@maxdow OK pour moi. Et je ne suis dispo ni le 7 mai ni le 31 mai. Et ma présence est peut-être moins nécessaire que pour les autres, donc si au final seul le 31 mai convient aux autres, je décline et vous me raconterez. ;-)

**Comment by val-bubbleflat** [comment]
Salut :)
Chez Bubbleflat on a une appli Vuejs en prod (on bosse dessus depuis un an, elle est en prod depuis juillet, 20k users). Notre application se doit d'être modulaire (en plus de notre site, on vend la même plateforme adaptée pour chaque client, avec des demandes propres à chacun --> un seul code pour des affichages différents selon le client). On peut donc faire un topo sur comment on arrive à ce résultat architecturalement/techniquement en tirant le meilleur de Vue.

**Comment by maxdow** [comment]
@mdartic parfait pour un retour de plus.

On aurait potentiellement 4 retours d'xp ce qui est génial. Si chacun propose 10min on peut en caller un autre. 

Est ce que vous pensez que 10min vous suffit pour un retour d'XP sur vos projets ? 

Pour la contrainte du jeudi c'était du temps ou il n'y avait pas le GDG . Aujourd'hui la dynamique est différente et le but du jeu est surtout de ne pas interférer avec d'autres conf.

**Comment by val-bubbleflat** [comment]
Pour nous 10min c'est nikel :)

**Comment by Tactless7** [comment]
Tout ça me parait bien ! 
Et pour les 10min, on adaptera le retour en fonction du temps :)

**Comment by ogadaki** [comment]
Pour moi 10 mins c'est largement suffisant ! :-)

**Comment by NotBad4U** [comment]
+1

**Comment by maxdow** [comment]
Bonjour à tous. 

On s'organise pour trouver une date . Ce ne serait pas avant le 21 mai donc ça vous laisse un peu le temps de préparer ;)

Au niveau des retours d'Xp, l'idéal serait que chaque retour puisse appuyer un avantage/inconvénient différent pour éviter de voir 4 ou 5 fois la même chose.

Niveau format cela peut être 2 slides : présentation du projet suivi d'un +/- sur l'utilisation de vue dans ce cadre.

Est ce que ça vous parle ?

**Comment by mdartic** [comment]
ok, parfait pour le timing à mon niveau.

Pour le format des retours d'xp, pourquoi pas, j'aurais tendance à laisser un peu de latitude à l'orateur s'il veut montrer des slides explicatives (capture d'écran / autre) qui pourrait appuyer ses avantages / inconvénients.

J'ajouterais un chrono pour avoir un timekeeper sur la durée de chq feedback histoire de ne pas pénaliser les collègues ?

**Comment by maxdow** [comment]
C'était une proposition autolimitante. Si le speaker se sent de faire plus de slides pour présenter le projet du moment que ça tient dans les 10 min aucun soucis. 
Sur 10 min on peut faire 10 slides ;)

Je serai la pour timer mais oui pourquoi pas disposer un chrono sur une tablette par ex

**Comment by fredericfalliere** [comment]
Salut les amis je viens de tomber sur ce fil de discussion par tweeter! Là où je bosse on a fait du vuejs, partie en prod, sur 3 apps webs et 1 app mobile (avec quasar).

De plus on fait aussi du angular 5... 

Si ce n'est pas trop tard pour faire une propal de talk, et rapidement, voici quelques points que je serais intéressé à présenter devant la communauté :
- comparaison avec angular5
- manager les données avec vuex
- architecture pour une app web de taille moyenne
- histoire de vuejs et philosophie (tweets d'Evan U)

Puis s'il y a des questions...

Voilà dites moi si ça pourrait éventuellement vous intéresser. Merci 🤩

**Comment by maxdow** [comment]
Bonjour tout le monde. Petit recap pour l'évenement 

On  table sur une présentation générale puis des retours d'XP de plusieurs intervenants sur différents profils de projets.

@mdartic présentation technique en collaboration avec @Tactless7
@Tactless7 retour XP Schoolmouv
@nnodot retour sur ton projet/experience "débutant"
@val-bubbleflat retour appli modulaire avc vue
@mdartic retour petit projet

30 min l'intro générale puis 10/15min par retour d'XP

@marcelfalliere ta proposition est très interessante, merci. Penses tu pouvoir tenir sur 10/15 min? Certains éléments peuvent rentrer dans la présentation générale ( du coup à synchro avec @mdartic et @Tactless7 )



2eme point : les dates

On aurait des dispos pour le jeudi 24 mai est ce que ça vous va ?

**Comment by Tactless7** [comment]
Le 24 mai pour moi c'est ok ! 

@marcelfalliere personne ne compte parler mobile avec Vue.js, si tu n'en parles pas lors du talk, je serais super intéressée d'avoir ton retour sur Qasar :)

**Comment by val-bubbleflat** [comment]
Ok pour moi aussi !

Et aussi vraiment intéressé par un avis sur quasar :)

**Comment by fredericfalliere** [comment]
Le 24 mai à priori ok pour moi.

@maxdow du coup oué 10-15 minutes dont une grosse partie sur le retour vuejs/quasar c'est 👌

**Comment by ogadaki** [comment]
OK pour le 24 mai. Et je dirais même plus : vivement le 24 mai ! :-)

**Comment by maxdow** [comment]
Allé vendu pour le 24 mai ;)
@marcelfalliere je te compte pour les retours d'XP parfait

**Comment by mdartic** [comment]
@maxdow bon, le 24 ok (puisque tt le monde est ok !), mais c'est la veille de Sud Web ? (où je vais, et c'est pas à côté !)
peux tu me préciser les créneaux habituels ? je dois m'organiser après pour le covoit vers Anduze (là où a lieu Sud Web)

**Comment by maxdow** [comment]
Ah oui en effet et cette année j'y vais pas je n'ai pas fait le rapprochement..
Le créneau habituel est 19h - 21h(max)

**Comment by fredericfalliere** [comment]
L'hébergement c'est bon ? Sinon ma boîte peut héberger!

**Comment by maxdow** [comment]
Oui on sera chez athome pour cet event mais merci :) peut être un prochain du coup.

**Comment by maxdow** [comment]
Hello tout le monde. Avant de balancer la com' pour les inscriptions, est ce que c'est toujours Ok pour vous sur la date du jeudi 24 mai et la trame ?

**Comment by mdartic** [comment]
Yep, ok pour moi.
Appel d'ailleurs à la populaschtroumpf, càd : 
@Tactless7, @nnodot, @val-bubbleflat, @marcelfalliere

Est ce que vous souhaitez qu'on se coordonne pour avoir une seule prèz, et on passe le relais à chacun quand c'est son tour ?
Dans l'idée, je pensais faire un reveal markdown, j'ai commencé qqs notes pour la partie présentation (on doit y bosser avec @Tactless7), mais on peut vous laisser un peu de place pour y injecter vos feedbacks ?

**Comment by ogadaki** [comment]
Je pense que le plus simple est que chacun gère sa présentation. Les sujets sont suffisamment isolés et ça laisse plus d'autonomie pour la préparation.

Mais c'est juste un avis. Si la majorité est pour mettre en commun, je suis ! :-)

**Comment by fredericfalliere** [comment]
Yes toujours ok pour le 24 mai.

Niveau prez ça me semble compliqué d'avoir des slides en commun, d'autant
plus que si des gens veulent montrer du code ou faire une démo, il faudra
leur machine.


Frédéric
@marcelfalliere

**Comment by mdartic** [comment]
Ok, je vais vous embêter juste une dernière fois, après j'arrête :-)
On s'est dit avec @Tactless7 que ce serait pertinent d'avoir une mise en contexte commune pour le feedback.
Une proposition serait ça : 

* taille du projet / équipe (nombre de jours / personnes)
* technos utilisées (front / back / tooling)
* pourquoi le choix de Vue.js
* avantages / inconvénients de l'utilisation de Vue.js
* si c'était à refaire ?

@nnodot, @val-bubbleflat, @marcelfalliere ça vous irait d'intégrer ça ?

J'imagine que la partie avantages / inconvénients on l'a tous.

L'idée est d'avoir des points de comparaison pour l'auditoire.

Les slides de la préz sont en cours de finalisation sur https://github.com/mdartic/vuejs-toulousejs-2018 et visibles sur http://vuejs-toulousejs-2018-05.surge.sh/ . Si vous voyez des coquilles, n'hésitez pas à créer des issues sur le projet.

**Comment by val-bubbleflat** [comment]
Salut,
Comme la présentation est demain, cela semble difficile de changer tout au dernier moment ...
Je ferai au mieux pour en parler, même rapidement :)

**Comment by mdartic** [comment]
Ah pas la peine de tout changer :-) une slide de résumé suffit ?

De mon côté c'est comme ça : x personnes (front / back), x mois de dév, telle techno front / back, volumétrie (faible de mon côté).

Ça ne me paraît pas trop difficile d'ajouter ça ?

**Comment by fredericfalliere** [comment]
Moué pourquoi pas ... çe donne le contexte de connaissance et d'xp du speaker au moins.

Perso je l'adapte un peu (par exemple les technos back c'est irrelevant imho)

**Comment by ogadaki** [comment]
OK pour moi. En ce qui me concerne ce sera vite fait. Débutant oblige... ;-)

Vous avez prévu de l'intégrer dans votre présentation ou on le fait de notre côté ?

**Comment by mdartic** [comment]
non pas prévu de l'intégrer,
mais si tes slides sont accessibles sur le web, et que le pc d'un autre te suffit, pas besoin d'amener le tiens :-)

**Comment by maxdow** [comment]
Salut la team VueJS. Est ce que tout va bien pour vous ? Avez vous besoin de quelque chose pour ce soir ?

**Comment by val-bubbleflat** [comment]
Salut, tout va bien pour moi a part un peu de stress :p

**Comment by maxdow** [comment]
Ce serait anormal de ne pas en avoir ;)

**Comment by Tactless7** [comment]
Même chose pour moi :) Un peu tendue mais besoin de rien !

**Comment by shprink** [comment]
...envie de toi?

**Comment by ogadaki** [comment]
Moi aussi tout est OK. J'ai juste besoin de me souvenir que ce soir pour une fois ce n'est **pas** au HarryCow... ;-)

**Comment by mdartic** [comment]
j'ai une question, on se pointe à quelle heure ? 18h30 ça va ?

pour info @Tactless7 j'ai fait une répé ici avec la team makina, la démo sera raccourcie, sinon ça va bien déborder. on s'arrêtera avant la mise en place du formulaire normalement.

**Comment by Tactless7** [comment]
Je compte venir pour 18h30 perso

**Comment by fredericfalliere** [comment]
Yo ! Moi j'arrive vers 19h pile pour le début :)

Y'aura besoin d'adaptateurs VGA/HDMI vers DisplayPort etc ... ? Au cas où, j'en ramène (j'ai un MacBookAir).

Et bon ben j'espère que ça le fera ... un peu stressé aussi. J'ai fait la prez à la team in-tact j'ai du rebosser un ou deux slides pas assez clairs.

En 10 Minutes ça va être shorty short. Et va falloir improviser en live pour pas répéter ce que les copains auront dit (surtout que je passe en dernier).

**Comment by mdartic** [comment]
Pas d'inquiétude, on demandera la bienveillance du public en début de séance.

**Comment by mdartic** [comment]
Je n'ai pas pris le temps de vous dire à tou-te-s merci pour vos talks.

Alors, 
Merci @Tactless7 pour avoir co-présenté ce meetup et ton feedback nourri sur un projet d'envergure, 
Merci @nnodot pour ta démo accessible à tou-te-s et qui a montré qu'on peut facilement monter sur ce framework, 
Merci @val-bubbleflat & ton collègue pour expliquer l'usage et des problématiques de projets conséquents
Merci @marcelfalliere pour ton feedback sur l'usage de cet écosystème.

Et merci @maxdow pour nous avoir lancer l'idée du talk.

J'aurais souhaité avoir un peu de temps supplémentaire, mais nous n'avons pas toujours été hyper organisés non plus sur le contenu et le respect du temps. 
(je ne vise personne en particulier, moi-même ayant fait une démo un peu longuette)

Je pense que le public a pu voir ce qu'était ce monstre du loch ness, donc la mission me semble remplie !

Merci pour le temps que vous avez pu consacrer à vos talks.

N'hésitez pas à diffuser autour de vous ce que vous apprenez, et venez échanger sur le slack de la communauté toulousaine !

A+

**Comment by ogadaki** [comment]
Et merci à toi @mdartic  pour cette belle introduction et présentation de Vue.js !

L'ensemble de la soirée m'a bien plu, j'ai l'impression que les gens étaient intéressés et du coup je pense que c'est une expérience à reproduire à l'occaz !

**Comment by Tactless7** [comment]
Merci à toi aussi @mdartic ! C'était une très chouette expérience de bosser et d'échanger avec toi sur cette prez

**Comment by fredericfalliere** [comment]
Yo ben encore merci plus j'y repense à cette soirée plus j'ai envie d'en faire d'autres :-) (en préparant plus, et stressant moins).

Pitte question cependant : la vidéo de la soirée, elle est dispo quelque part ? Sur YT y'a le replay du live, mais il n'y a pas le son :'( 

Merci, bises!
