### ISSUE TITLE
[Smart-contracts under attack] Paul Marty (polo46) + Damien Lecan (dlecan)

### ISSUE THREAD

**Issue by dlecan** [GDGToulouse/meetup-cfp#56]
Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you - Speaker #1

* Name: Damien Lecan
* Link to profile picture (best quality you have): https://www.linkedin.com/in/damienlecan/
* Job title: CTO
* Company: Space Elephant
* Twitter handle: dlecan
* Experience as a speaker:
    - [ ] beginner
    - [ ] advanced
    - [X] expert
* Links to your previous events, videos etc. : 
Tous les events où j'ai été speaker : https://blog.dlecan.com/blog/categories/speaker/
La plupart ont des vidéos.

## About you - Speaker #2

* Name: Paul Marty
* Link to profile picture (best quality you have): https://www.linkedin.com/in/paul-marty/
* Job title: Security Consultant
* Company: Orange Cyberdefense
* Twitter handle: polo46
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Links to your previous events, videos etc. : None

---

## Description of your talk (200 characters at least)
Les smart contracts automatisent des tâches autrefois réservées à des tiers de confiance. Ces petits programmes décentralisés peuvent gèrer l'équivalent de millions de dollars et des bugs ou autres joyeusetés y causent régulièrement la perte ou le vol d'importantes sommes d'argent ;-)

Dans cette présentation, vous verrez un exemple d'implémentation "naïve" de *smart contract*, des exemples d’attaques et des recommandations d’architecture et de sécurité.

Contenu de la présentation:

- Introduction
- Rappels sur la blockchain et Ethereum (architecture, Dapp, transactions, gas, smart-Contrat, etc.).
- Implémentation "naïve" d'une application décentralisée
- Démonstration d’attaques
- Conclusion & bonnes pratiques
- Ressources
---

## Miscs

* Tags (e.g: angular, android, web, iot) : blockchain, ethereum, smart-contract, solidity, security, web3
* Talk level :
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Length (max 45 min) : 
* Format:
    - [x] Slides
    - [x] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): Juin 2018

**Comment by shprink** [comment]
Hello, merci pour cette proposition! 

On peut en parler via un chat? Genre sur twitter? https://twitter.com/julienrenaux

Merci

**Comment by shprink** [comment]
Bonjour,

l'evenement est prevu le 5 Juin dans les locaux de iBP a Balma Gramont. Essayez de rentrer le sujet dans les 45 min questions incluses.

Je m'occupe de creer l'evenement sur Meetup.

Merci!

**Comment by shprink** [comment]
Bonjour,

le meetup est annonce a nos membres depuis 2min https://www.meetup.com/GDG-Toulouse/events/250099870/

n'hesitez pas à le partager.

Merci
