### ISSUE TITLE
[PWA, où en sommes-nous aujourd'hui ?] Alexandra JANIN

### ISSUE THREAD

**Issue by lellex** [GDGToulouse/meetup-cfp#57]
Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you

* Name: Alexandra JANIN
* Link to profile picture (best quality you have): https://avatars0.githubusercontent.com/u/4436239?s=400&v=4
* Job title: Développeuse front-end
* Company: Makina Corpus
* Twitter handle: lellexindo
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 

---

## Description of your talk (200 characters at least)

J'ai 2 idées de sujets en tête à propos des PWA 

**- Proposition 1 : PWA : où en sommes-nous aujourd'hui ?**
Présentation générale sur ce que sont les PWA, à quels critères doit répondre une application pour être qualifiée de "progressive web app" ? Rapide présentation des services workers, de la cache API et du manifest. Les outils pour mettre en place une PWA (lighthouse, workbox,...), quel compatibilité ?

Ce serait une présentation pas vraiment technique, qui peut s'adresser aussi bien aux développeurs qu'à d'autres profils moins tech.

**- Proposition 2 : Comprendre les service workers et mettre en place une stratégie de cache**
Qu'est-ce que le cycle de vie d'un worker ? Comment communiquer avec le javascript du site et écouter des événements. Démonstration de différentes stratégies de mise en cache via la Cache API. Quelle stratégie utiliser pour mon application ? De quelle manière proposer une mise à jour du cache à l'utilisateur ?

Sujet assez technique avec beaucoup d'exemples de code, s'adresse plutôt à des dev mais aussi aux UX designers (par exemple) pour le choix des stratégies de cache.

---

## Miscs

* Tags (e.g: angular, android, web, iot) : pwa, service worker, javascript
* Talk level :
    - [x] beginner
    - [x] advanced
    - [ ] expert
* Length (max 45 min) : 
    - Soit l'un ou l'autre des sujets ci dessus en 20-25 min (+ questions ?). 
    - Soit les 2 combinés : présentation globale des pwa + gros sujet technique sur les service workers en 45 minutes ça me semble faisable.
* Format:
    - [x] Slides
    - [ ] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): Dispo tout le temps, peu importe

Je précise que je n'ai jamais fait de présentation, ce serait une première 😄

**Comment by shprink** [comment]
Merci Alexandra!

Ca pourra faire une super soiree Web! Par contre on a bouclé la saison des meetups. On reprend en Septembre donc on a le temps d'en reparler :)

**Comment by maxdow** [comment]
Salut @lellex . Est ce que tu serais ok pour programmer ton talk fin novembre ?

**Comment by lellex** [comment]
Ok pour fin novembre ;) j'ai pas de contraintes au niveau de la date pour le moment, préviens moi quand tu as plus de précisions. Merci !

**Comment by maxdow** [comment]
@lellex finalement une soirée tests front-end se précise alors je pense plutot faire le sujet PWA début 2019 si tu n'y vois pas inconvénients 🙈 . On pourrait tenter de mutualiser avec un sujet mobile par exemple.

**Comment by mdartic** [comment]
@maxdow tu as déjà un sujet mobile ou pas ? (je regarde nativescript-vue en ce moment... )

**Comment by shprink** [comment]
NativeScript 😍

**Comment by maxdow** [comment]
il me semble que non. Si tu peux proposer pour le mixer avec le sujet PWA ce serait parfait ;)

**Comment by lellex** [comment]
Moi ça me va !

**Comment by lellex** [comment]
Au fait pour finir j'ai fait un mix des 2 propositions initiales. Je peux la faire en 25-30 minutes.
Voici une description qui convient mieux : 

- Présentation générale sur ce que sont les PWA, rapide comparatif avec les autres types d'applications
- Explications sur les services workers
- Les différents moyens de stocker des données pour le mode offline et présentation de la cache API
- Les outils pour mettre en place une PWA (lighthouse, workbox,...)
- Comment faire des Push Notifications

**Comment by mdartic** [comment]
@maxdow j'ai vu que tu as une issue sur React Native par Antoine Rousseau => il attend depuis un petit moment on dirait, est ce que ce serait adapté avec la session d'Alex ?

sinon j'ai publié la #65 !

**Comment by maxdow** [comment]
Salut @lellex , est ce que c'est toujours bon pour toi pour faire cette conf ? 
On pense à avril est ce que cela te conviendrait ?  as tu des contraintes / préférences ?

**Comment by maxdow** [comment]
Ce serait plutot pour mai avec @ilaborie .

**Comment by lellex** [comment]
Hello
Ok pour moi en avril, en mai ça dépend je suis dispo que la semaine du 27 au 31 mai.
