### ISSUE TITLE
[Gitlab | CI] Philippe Charrière | Logan Weber | Kevin Davin

### ISSUE THREAD

**Issue by davinkevin** [GDGToulouse/meetup-cfp#58]
Proposition en cours d'élaboration, mais le ticket est créé afin de "réserver" un slot. 

Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you

* Name: Philippe Charrière | Logan Weber | Kevin Davin & cie
* Link to profile picture (best quality you have): TBD
* Job title: TBD
* Company: Gitlab | Airbus | Stack Labs
* Twitter handle: @k33g_org | @neonox31 | @davinkevin
* Experience| as a speaker:
    - [X] beginner
    - [X] advanced
    - [X] expert
* Links to your previous events, videos etc. : 

---

## Description of your talk (200 characters at least)

Présentations dédiées à l'univers Gitlab, avec présentation de la solution (repository, board, issue, code review, epic...) et sur la partie CI (définition, extension, différences !)

---

## Miscs

* Tags (e.g: angular, android, web, iot) :
* Talk level :
    - [X] beginner
    - [X] advanced
    - [ ] expert
* Length (max 45 min) : Certainement 2 présentations consécutives en mode présentation + rex
* Format:
    - [X] Slides
    - [X] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): Potentiellement pour le slot de Septembre

La proposition sera étoffée par les différentes intervenants d'ici là (/cc @k33g )

**Comment by k33g** [comment]
:)
ᐧ

**Comment by shprink** [comment]
Hello,

Bonne nouvelle nous avons une salle plein centre ville de reservee pour le Jeudi 27 Septembre.

Nous serons chez Athome, 32 Rue des Marchands, 31000 Toulouse, France: https://photos.app.goo.gl/dwj1faiBdB0L1YsS2

Pouvez vous etoffer la description de l'event et chacun remplir les champs suivants SVP:

* Link to profile picture (best quality you have):
* Job title:

nous avons besoin de tout ca pour remplir l'event sur meetup.

Merci

**Comment by shprink** [comment]
📣 hello?

**Comment by Neonox31** [comment]
Hello,

Voici pour ma part
- **Profile picture :** https://www.gravatar.com/avatar/1d25b8b61b0d6bd8602c94271faa4c8c?s=2048
- **Job title :** Software automation engineer at Airbus DS

**Comment by shprink** [comment]
Event cree: https://www.meetup.com/GDG-Toulouse/events/253787471/

Image thumbnail a venir

**Comment by k33g** [comment]
Avec du retard:

**Titre**: Quelques trucs pour se former "en douceur" à GitLab, GitLab CI & CD avec Fn Project

**Abstract**:

Alors, oui, c'est un titre long et un peu compliqué, donc je m'explique 😉. Le truc sympa avec GitLab, c'est que même si c'est un outil collaboratif, on peut se l'installer tout seul dans son coin et faire les choses les pires "en cachette" (j'appelle ça de l'expérimentation). Et en plus, on peut le faire en mode off-line dans le train ou à la campagne chez mémé qui n'a pas le wifi.

Je vais donc aborder les sujets suivants:
- GitLab: comment l'installer avec Vagrant (un jour j'apprendrais Docker 😉)
- GitLab Runner: installation et utilisation: 1er script de CI

Ensuite, le moyen le plus simple que j'ai trouvé pour m'entraîner à faire de l'intégration et du déploiement (en continu) sur mon poste en local, c'est **Fn project** un projet de **FaaS** facile à installer, donc nous verrons comment:

- créer une Docker registry privée (je ne connais toujours pas Docker, mais c'est super simple)
- installer et utiliser un serveur **Fn project** (oui je sais c'est un nom "bizarre", mais c'était le projet le plus facile à installer)
- créer un runner pour déployer des fonctions sur ce serveur
- et pour finir nous verrons comment faire des Review Apps avec tout ça (donc déployer des feature branches sur un serveur de développement)

Cette présentation s'adresse à un public plutôt débutant, mais les moins débutants sont les bienvenus, ils pourront apporter leur pierre à l'édifice sur certains points "existentiels".

A la fin de la présentation, vous aurez les outils nécessaires pour vous créer une infrastructure "DEVOPS" virtuelle et faire vos armes.

**Comment by k33g** [comment]
@davinkevin @Neonox31 @shprink ☝️

**Comment by davinkevin** [comment]
Pour notre partie: 

---
A l'image de Perceval et Karadock, Logan et Kevin reviennent d'une quête dans la contrée de Gitlab et vont vous compter leurs aventures pleines découvertes et de rebondissements. L'on espère que Père Blaise réussira à prendre des notes...

Lors de cette quête, il a été nécessaire de mettre en place une intégration continue pour une armée de développeurs sanguinaires qui avaient plein de besoins tout bizarres... Et à la force de leur épée, de leur courage et pas du tout de l'aide de Merlin (qui sait toujours rien faire...), Logan et Kevin mis à disposition une CI complète avec job, stage, intégration avec des outils externes (PostgreSQL, Artifactory, Google Cloud Platform...) tout en la gardant simple et versionnable.

Ils finiront même par la présentation d'un récent sortilège qui permet d'envoyer leur CI dans le Cloud de Google avec Kubernetes. Cela donne une solution hautement scalable et performante, à la demande !avec Google Kubernetes Engine afin de vous présenter une solution scallable et automatique !

---

L'on a par logique quelques éléments en commun, mais nous les passerons rapidement.
