### ISSUE TITLE
[QUIZZ RXJS - comment tirer le meilleur de RXJS ?] Philippe Beroucry & Laurent Wroblewski

### ISSUE THREAD

**Issue by choucry13** [GDGToulouse/meetup-cfp#61]
Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

## About spearkers

* Name: Philippe Beroucry
* Link to profile picture (best quality you have): [PB](https://avatars0.githubusercontent.com/u/9515435?s=88&v=4)
* Job title: Développeur Front-end
* Company: IT-CE
* Twitter handle: [PB](https://twitter.com/philou_philou_p)
* Experience as a speaker:
    - [ ] beginner
    - [X] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
https://www.slideshare.net/choucry/a-la-conqute-de-lagilit-chez-les-dveloppeur
https://www.youtube.com/watch?v=4Q76ANm8IwI

* Name: Laurent Wroblewski
* Link to profile picture (best quality you have):
[LW](https://pbs.twimg.com/profile_images/932349027500294144/rK6Ot6Yu_400x400.jpg)
* Job title: Développeur Front-end
* Company: I-BP
* Twitter handle: [LB](https://twitter.com/LaurentWrob)
* Experience as a speaker:
    - [ ] beginner
    - [X] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
http://slides.com/laurentwroblewski
---

## Description of your talk (200 characters at least)
Aujourd'hui Rxjs est devenu une bibliothèque incontournable en matière de programmation réactive. Nous verrons autour d'un grand quizz tous les moyens que propose rxjs pour vous aider dans la réalisation de vos applications web. 
Mon petit doigt me dit qu'il y aura une grande récompense pour le vainqueur ^^.

---

## Miscs

* Tags (e.g: angular, android, web, iot) : rxjs, angular, web component
* Talk level :
    - [X] beginner
    - [X] advanced
    - [X] expert
* Length (max 45 min) :  45 minutes
* Format:
    - [X] Slides
    - [X] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): le 19 septembre

**Comment by shprink** [comment]
Event cree: https://www.meetup.com/GDG-Toulouse/events/253786678/

Image thumbnail a venir
