### ISSUE TITLE
[Statecharts - Moins de bugs dans nos interfaces ] Gilles Debunne

### ISSUE THREAD

**Issue by GillesDebunne** [GDGToulouse/meetup-cfp#62]
Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

## About you

* Name: Gilles Debunne
* Link to profile picture (best quality you have): https://cloudinary-a.akamaihd.net/hopwork/image/upload/dpr_2.0/etn9it6jsyy2cqaiwbll.webp
* Job title: Développeur Freelance
* Company: QDC
* Twitter handle: @gdebunne
* Experience as a speaker:
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
Speaker aux deux précédentes éditions du DevFest

---

## Description of your talk (200 characters at least)
On parle ici d'interfaces graphiques, d'interactions avec l'utilisateur et de gestion de l'état. Et des bugs associés.

Les interfaces de nos applications doivent fondamentalement gérer un état, de façon cohérente. Mais avec l'asynchrone, les cas particuliers, les animations, des scenarios plus complexes et surtout au fil des demandes d'évolutions, comment éviter l'explosion combinatoire, garder la maîtrise de son code et éviter les bugs ? 

Le formalisme *StateCharts*, récemment remis au goût du jour dans plusieurs conférences, apporte une solution à ces problèmes. L'état n'est plus représenté par un ensemble hétérogène de booléens qu'on espère rester cohérent, mais par un automate. Plus complexe à mettre en place, mais permettant un dialogue avec les designers, des tests automatiques et une bien meilleure évolutivité, je le présenterai et ferai un retour d'expérience sur son utilisation dans mes applications.

---

## Miscs

* Tags (e.g: angular, android, web, iot) : UX, UI, React, Statecharts
* Talk level :
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Length (max 45 min) : 40 min
* Format:
    - [x] Slides
    - [ ] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): à partir d'octobre 2018

**Comment by maxdow** [comment]
Bonjour @GillesDebunne . On essaye d'organiser ça pour fin novembre si c'est bon pour toi

**Comment by GillesDebunne** [comment]
Ça marche, merci pour le retour. Prévenez-moi dès que ça se précise.

Gilles

**Comment by maxdow** [comment]
bonsoir @GillesDebunne , derniere semaine de novembre ça irait pour toi ?

**Comment by GillesDebunne** [comment]
Hello,

Oui. Je vais essayer de préparer la présentation maintenant, car j'ai un
peu de temps.

**Comment by maxdow** [comment]
On a bloqué la date du 29 novembre, est ce que c'est ok pour toi ?

**Comment by GillesDebunne** [comment]
Oui, je bloque la date...
