### ISSUE TITLE
Et si on testait notre front-end ?

### ISSUE THREAD

**Issue by euZebe** [GDGToulouse/meetup-cfp#64]
Présentation de Cypress.io, framework de test end-to-end.
- tour d'horizon des solutions existantes
- objectifs et public cible de Cypress 
- Comment s'écrivent les tests
- interface d'exécution 
- côté CI
- retour d'XP

**Comment by maxdow** [comment]
Merci pour ta proposition :) 
Combien de temps ferait ta présentation ? Des préférence en disponibilité ?

**Comment by euZebe** [comment]
Je pense qu'on peut compter 45 minutes. Je suis en train de la préparer ; elle doit pouvoir être dispo dans 1 mois.

**Comment by davinkevin** [comment]
J'attend impatiemment celle ci 🤩

**Comment by euZebe** [comment]
@davinkevin Je n'ai par contre aucune expérience dans un outil concurrent ; j'ai lu quelques points négatifs sur Selenium mais peut-être les surcouches (nightwatch, protractor, etc.) comblent-elles tout ou partie de ces lacunes.
Toujours est-il que le sujet e2e mérite bien au moins un talk, à mon avis.

**Comment by maxdow** [comment]
un meetup derniere semaine de novembre c'est bon pour toi @euZebe ?

**Comment by euZebe** [comment]
Oui.

**Comment by maxdow** [comment]
On a bloqué la date du jeudi 29 novembre, est ce que c'est ok pour toi ?

**Comment by euZebe** [comment]
C'est bon.
