### ISSUE TITLE
retour d'expérience sur l'utilisation de Firebase chez Diner

### ISSUE THREAD

**Issue by kidz55** [GDGToulouse/meetup-cfp#68]
Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you

* Name: Thibault Gloaguen
* Link to profile picture (best quality you have): https://pbs.twimg.com/profile_images/1035584482844319744/7pkCSWux_400x400.jpg
* Job title: fullstack developer
* Company: Diner
* Twitter handle:
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
https://www.youtube.com/watch?v=OBpkL-AYBYI&feature=youtu.be
---

* Name: Paul Gaucher
* Link to profile picture (best quality you have): https://pbs.twimg.com/profile_images/864500782883667968/-DbST3lV_400x400.jpg
* Job title: fullstack developer
* Company: Diner
* Twitter handle:
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert

## Description of your talk (200 characters at least)
Ce talk portera sur la façon dont nous utilisons Firebase Chez Diner, de la mise en production, des cloud functions, du remote config ou encore du realtime database en passant par le reporting avec Big Query ou encore les crons gérés par GCP.
Nous allons montrer à quel point il est facile / utile d'utiliser firebase dans une application.
---

## Miscs

* Tags (e.g: angular, android, web, iot) :
Firebase, mobile, cloud functions, GCP
* Talk level :
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Length (max 45 min) : 
30-40 minutes
* Format:
    - [x] Slides
    - [ ] Live coding
    - [x] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX):à partir de Janvier

**Comment by gdemiollis** [comment]
C'est validé pour le 17 janvier!
