### ISSUE TITLE
[Everything You Should Know About the New Angular CLI] Amadou Sall

### ISSUE THREAD

**Issue by ahasall** [GDGToulouse/meetup-cfp#70]
Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

## About you

* Name: Amadou Sall
* Link to profile picture: https://res.cloudinary.com/ahasall/image/upload/v1540629012/ahasall.jpg
* Job title: Frontend Software Engineer
* Company: Air France
* Twitter handle: @ahasall
* Experience as a speaker:
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
    - https://youtu.be/aMYdbhqKiHY

---

## Description of your talk
Angular CLI est un puissant outil qui permet d'augmenter notre productivité lorsqu'on développe des applications Angular. Avec Angular CLI, on peut générer des "blueprints", développer, tester, et "builder" nos applications. C'est le meilleur starter-kit qui existe pour les applications Angular.

Depuis la version 6, plus puissant et plus générique, Angular CLI a introduit plein de nouvelles fonctionnalités notamment les workspaces, les architectes, les builders, la possibilité de développer des librairies, et mon préféré, les Schematics. Les schematics sont le sujet principal de cette présentation. Ils nous permettent de créer nos propres templates de génération de code, d'ajouter un framework ou une librairie à notre application en une seule commande, de mettre à jour/migrer nos applications.

Après cette présentation, vous allez avoir une vision d'ensemble des nouvelles fonctionnalités du CLI notamment:

- le support multiprojets,
- le développement d'une librairie avec le CLI,
- les architectes,
- les builders,
- comment créer son propre schematic,
- comment faire le bon choix entre snippets, schematics, et une librairie.
---

## Miscs

* Tags: Angular
* Talk level:
    - [x] beginner
    - [x] advanced
    - [x] expert
* Length (max 45 min) : 30 - 40 min
* Format:
    - [x] Slides
    - [x] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX):

**Comment by davinkevin** [comment]
Tu vas présenter la partie builders aussi? 

En tout cas, pour moi 👍

**Comment by ahasall** [comment]
> Tu vas présenter la partie builders aussi?

Oh ! Surement, j'ai oublié de le mettre dans l'abstract.

**Comment by shprink** [comment]
Hello @ahasall !

Tu serais dispo pour faire cette presentation chez iBP en Fevrier?

**Comment by ahasall** [comment]
Hello @shprink,
Oui Février ça me va.

**Comment by shprink** [comment]
ok super, commence a te preparer alors, si tu veux te preparer vers janvier en nous faisant la prez pas de probleme.

**Comment by ahasall** [comment]
Je suis quasiment prêt. Mais je veux bien faire une répétition en Janvier.

**Comment by shprink** [comment]
Hello. Le 21 février c'est bon pour toi?

**Comment by ahasall** [comment]
Salut Julien,
Le 21/02 c'est bon pour moi.

**Comment by shprink** [comment]
ok je confirme avec ibp et je te tiens au courant

**Comment by shprink** [comment]
(ce sera chez eux)

**Comment by ahasall** [comment]
Super.
À bientôt.

**Comment by shprink** [comment]
https://www.meetup.com/GDG-Toulouse/events/258494431/

**Comment by ahasall** [comment]
Super 👍
