### ISSUE TITLE
[Retour d'expérience sur la mise en place d'un écosystème Angular au sein d'une entreprise] Philippe Beroucry Laurent Bonzom Benoît El Amrani

### ISSUE THREAD

**Issue by belamrani** [GDGToulouse/meetup-cfp#75]
Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you

* Name: Beroucry/Bonzom/El Amrani
* Link to profile picture (best quality you have):
* Job title: Développeurs Front-End
* Company: I-BP et IT-CE
* Twitter handle: bentah31 , philou_philou_p
* Experience as a speaker:
    - [X] beginner
    - [ ] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 

---

## Description of your talk (200 characters at least)
Angular a été choisi pour la mise en place des nouvelles applications web au sein de notre entreprise. La mise en place de ce Framework a nécessité la réalisation d'un certain nombre de chantiers. Le but de ce talk est de vous partager notre retour d'expérience sur environ 2 ans sur cette techno. De l'architecture globale des applications à la mise en place d'une industrialisation en continue, nous avons mis en place différents procédés. 
Nous aborderons les points suivants lors de cette présentation :
- Industrialisation des applications et des librairies.
- Mise en place d'une core team pour la gestion de la stack technique et des besoins transverses aux différents projets.
- Stratégie de mise à jour de la stack technique sans impacter les besoins métiers en continue.
R&D
- Partage de connaissances entre développeurs.
- Solution de toolings pour la qualité du code

## Miscs

* Tags (e.g: angular, android, web, iot) : Angular
* Talk level :
    - [ ] beginner
    - [X] advanced
    - [ ] expert
* Length (max 45 min) : 45min
* Format:
    - [X] Slides
    - [ ] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): février 2019

**Comment by shprink** [comment]
Merci! Le 21 février ça vous va ?

**Comment by belamrani** [comment]
Yes 21 février impec 👌

**Comment by choucry13** [comment]
allez je réserve les billets du coup .... mdr

**Comment by shprink** [comment]
https://www.meetup.com/GDG-Toulouse/events/258494431/
