### ISSUE TITLE
[Flutter, et en vrai ça donne quoi?] Laurent Wroblewski

### ISSUE THREAD

**Issue by LWroblewski** [GDGToulouse/meetup-cfp#76]
## Le speaker
Laurent Wroblewski, développeur full stack indépendant

Twitter: https://twitter.com/LaurentWrob

## Sujet de la conférence
Flutter est un SDK open-source de création d'applications mobiles récent : sa version finale est sortie en Décembre dernier. Et pourtant, il explose déjà tous les compteurs de hype! Et pour cause, avouons que le bébé a quelques atouts pour lui :
 * Créé par Google, et basé sur le langage Dart (Google également).
 * Le SDK officiel de développement d'applications pour le futur OS Google Fuchsia.
 * Du multi-devices sans la nécessité de passer par un bridge Javascript.
 * Un moteur de rendu perso pour de meilleures performances.
 * Un mantra "everything is widget".

Mais qu'en est-il en réalité ? Une fois passé la création du "Hello World", l'utilisation/création de composants spécifiques, les performances, les fonctionnalités natives ou encore l'intégration continue répondent-ils vraiment aux standards de qualité de l'industrie ?

## Informations diverses
 * Thématique, Labels : Flutter, Dart
 * Niveau de difficulté : débutant
 * Durée : 40min
 * Format : slides, live-coding
 * Langue : FR
 * Dispo: Mars 2019

**Comment by choucry13** [comment]
hate de voir çà ^^

**Comment by shprink** [comment]
Et voila une soirée 100% Flutter toute trouvé! @Kleak aura surement un autre sujet à proposer :)
