### ISSUE TITLE
[Lightning Angular Open Source] - Various artists

### ISSUE THREAD

**Issue by shprink** [GDGToulouse/meetup-cfp#8]
Bonjour,

Vous etes le createur d'une librairie Open Source Angular (preference pour >=2 mais ng1 ok) et vous souhaitez la presenter durant un de nos meetups?

![register](https://media.giphy.com/media/3otPorfb8Lu7wjKllm/giphy.gif)

## Informations diverses
* Durée (max 45 min) :  10 min par projet max

**Comment by shprink** [comment]
Julien Renaux: [wordpress-hybrid-client](https://github.com/shprink/wordpress-hybrid-client)

**Comment by davinkevin** [comment]
DAVIN Kevin [AngularStompDK](https://github.com/davinkevin/angularStompDK) et peut être sa version 2+

**Comment by choucry13** [comment]
Bonjour @shprink , j'ai crée des librairies dans le cadre de ma mission. C'est publié dans un nexus en interne. Mais je peux vous proposer en 10 minutes comment industrialiser et publier une lib Angular et faire un exemple live.
Çà peut vous intéresser ? Si oui, je crée une issues dans ce sens.

**Comment by shprink** [comment]
Si c'est du Angular > 2 avec NgModule, AOT et Lazy loading c'est SUPER interessant. Les gens (moi aussi o_O) galerent pas mal sur tout ca! Go go go issue :)

**Comment by shprink** [comment]
Bon on ferme ca, pas assez de propositions
