### ISSUE TITLE
[QUELLE PROBLÉMATIQUE RÉSOUT BAZEL ?] Philippe Beroucry

### ISSUE THREAD

**Issue by choucry13** [GDGToulouse/meetup-cfp#84]
Language of the talk: 
-  🇫🇷

## About Me

* Name: Philippe Beroucry
* Link to profile picture (best quality you have): https://pbs.twimg.com/profile_images/572880932849512448/6RobPMJ__400x400.jpeg
* Job title: Développeur
* Company: Ngking
* Twitter handle: 
* Experience as a speaker:
    - [x] beginner
* Links to your previous events, videos etc. : 
https://www.youtube.com/watch?v=HTtBPWEkgO8&t=15s 
https://www.meetup.com/fr-FR/aixjs-org/events/258668063/ 
https://www.meetup.com/fr-FR/Groupe-HN-Aix/events/261224084/ https://slides.com/philippeberoucry/deck#/

---

## Description of your talk (200 characters at least)
Bazel est un outil open source développé par Google. 
Le but de ce talk est de vous montrer l’énorme plus value que peut vous apporter cet outil pour l’ensemble de vos applications. Cette introduction vous permettra de comprendre son fonctionnement et son enjeu pour les applications de demain.

---

## Miscs

* Tags (e.g: angular, android, web, iot) : #angular #web #mobile #software
* Talk level :
    - [X] beginner
* Length (max 45 min) :  30 minutes
* Format:
    - [X] Slides
    - [X] Live coding
* Availability (e.g: ASAP, before/after XXX): janvier 2020

**Comment by gdemiollis** [comment]
C'est pas que Web : Android, iOS, Java backend

**Comment by choucry13** [comment]
Hello, c'est dans le cadre du web dans mon cas avec des frameworks comme angular et react. Je ferai sans doute une démo sur de l'android.
