### ISSUE TITLE
[Angular Material ou Bootstrap ? Pourquoi choisir !] Amadou Sall & Jerome Djebari

### ISSUE THREAD

**Issue by ahasall** [GDGToulouse/meetup-cfp#85]
Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

### Amadou Sall
* Name: Amadou Sall

* Company: Air France-KLM
* Job Title: Frontend Software Engineer
* Website / Blog: https://www.amadousall.com
* Twitter Handle: ahasall
* Profile Picture: https://res.cloudinary.com/ahasall/image/upload/v1540629012/ahasall.jpg
* Experience as a speaker:
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Links to your previous events, videos: [https://www.amadousall.com/speaking/](https://www.amadousall.com/speaking/)

### Jerome Djebari
* Company: Air France-KLM
* Job Title: Software Engineer
* Twitter Handle: JDjebari
* Profile Picture: https://res.cloudinary.com/ahasall/image/upload/v1570109437/jerome.jpg
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert

## Description of your talk (200 characters at least)

Angular Material ET Bootstrap pour votre prochaine application Angular ? Ça n'a aucun sens, n'est-ce pas ? La première fois que j'ai proposé à mes collègues de mixer les deux, ils se sont tous moqués de moi. Mais aujourd'hui, ils sont devenus fans de cette approche, car ça marche du feu de Dieu !

Dans cette session, nous allons voir comment on peut tirer parti du meilleur des deux mondes pour créer des applications Angular qui soient jolies, maintenables, et responsives, et ce, avec très peu de CSS.

## Miscs

* Tags (e.g: angular, android, web, iot): Angular
* Talk level :
    - [x] beginner
    - [x] advanced
    - [x] expert
* Length (max 45 min) : 30 minutes
* Format:
    - [x] Slides
    - [x] Live coding (may be)
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): ASAP

**Comment by ahasall** [comment]
Salut @shprink, j'ai mis à jour le talk pour rajouter mon collègue Jerome Djebari.

**Comment by maxdow** [comment]
Bonjour. Est ce que vous seriez prêt pour donner cette présentation le 17 octobre prochain ?

**Comment by ahasall** [comment]
Hello @maxdow, est-ce possible de le faire le mardi 15 ou le mercredi 16 ?
On peut maintenir la date du 17 si ce n'est pas possible.

**Comment by maxdow** [comment]
Les créneaux sont malheureusement assez figés du coup si tu peux le 17 c'est top

**Comment by ahasall** [comment]
Okay. Pas de soucis pour le 17. Je préviens mon collègue.

**Comment by maxdow** [comment]
Merci :) on met ça en place
