### ISSUE TITLE
[Introduction à Android Things] Marc Plano-Lesay

### ISSUE THREAD

**Issue by JulienDelRio** [GDGToulouse/meetup-cfp#9]
{ Veuillez remplir ce template pour nous aider à en savoir plus.
Pour le titre de l'issue, merci de respecter cette notation : [NOM DE VOTRE CONFERENCE] Prénom Nom }

## Le speaker
Marc Plano-Lesay, développeur Android @Kernald

## Sujet de votre conférence
Introduction à Android Things

## Description de votre conférence
A remplir...

## Informations diverses
* Thématique, Labels : Android Things, IoT
* Niveau de difficulté (débutant|avancé|confirmé) : A remplir...
* Durée (max 45 min) : A remplir...

**Comment by EmmanuelVinas** [comment]
@Kernald est ce que tu peux remplir un peu plus le sujet de la conf.

**Comment by Kernald** [comment]
Ouip, je m'en occupe dans l'après-midi. J'ai commencé à préparer un peu le terrain [là-dessus](https://enoent.fr/blog/2017/01/06/android-things-first-look/), globalement je vais suivre la même trame sur la présentation.

**Comment by Kernald** [comment]
## Le speaker
Marc Plano-Lesay, développeur Android

## Sujet de votre conférence
Introduction à Android Things

## Description de votre conférence
Introduction à Android Things : qu'est-ce que c'est, de quoi c'est composé, comment ça s'utilise, à quoi ça peut servir…

## Informations diverses
* Thématique, Labels : Android Things, IoT
* Niveau de difficulté (débutant|avancé|confirmé) : débutant
* Durée (max 45 min) : 45 minutes
* Format (slides, live-coding, les deux): Slides principalement, peut-être un peu de code montré (sans doute sur les slides), une démo pourrait être intéressante, mais j'ai un peu de mal à voir comment présenter ça. Si quelqu'un a une suggestion là-dessus, je suis preneur, je peux amener un Raspberry Pi et quelques composants électroniques sur place
