### ISSUE TITLE
[REX : Comment ne pas scale une application Flutter]

### ISSUE THREAD

**Issue by JustDravee** [GDGToulouse/meetup-cfp#92]
Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

## About you

* Name: [GDPR - Expired]
* Link to profile picture (best quality you have): [GDPR - Expired]
* Job title: [GDPR - Expired]
* Company: [GDPR - Expired]
* Twitter handle: [GDPR - Expired]
* Experience as a speaker:
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 
**NullPointerException**
---

## Description of your talk (200 characters at least)
Voilà maintenant 1 an que la première version "production ready" de Flutter est sortie. De nombreux cours et tutos sont disponibles et peuvent aider à commencer le développement de son propre produit. Cependant, la montée en complexité d'une application peut vite rendre le socle de base inadapté. Par exemple, sans structure, je me suis retrouvé avec plus de 1000 lignes de logiques dans le même fichier.

Depuis ces 6 derniers mois, un avocat, un commercial et moi-même préparons le lancement d'une application Flutter. Celle-ci est encore en développement. Cependant, de nombreuses problématiques ont été soulevées au début et en cours de route telles que : la scalabilité, la maintenabilité, le choix des dépendances ou le coût sur la durée des outils tiers (comme Firebase ou Agora.io).

Je vous propose un talk "retour d'expérience" sur les leçons apprises jusqu'ici sur les différents choix initiaux et les faux-pas rencontrés lors du développement de cette application.

---

## Miscs

* Tags (e.g: angular, android, web, iot) : flutter, agora, firebase, mobile
* Talk level :
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Length (max 45 min) : 30 min
* Format:
    - [x] Slides
    - [ ] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): décembre 2019

**Comment by kevinabrioux** [comment]
@DylanPokun toujours motivé pour présenter ce sujet ?

**Comment by kevin-sakemaer** [comment]
Déjà fait à Flutter interact 😉
J'ai oublié de close

**Comment by kevinabrioux** [comment]
Honteux cette gestion @Kleak
