### ISSUE TITLE
Kotlin MultiPlatform: Day 365

### ISSUE THREAD

**Issue by jfaixo** [GDGToulouse/meetup-cfp#94]
Language of the talk: 
- [X] 🇫🇷
- [ ] 🇬🇧

## About you
Rémy et moi-même sommes deux passionnés de développement, respectivement pro iOS et pro Android... Let's fight !

- Name: Rémy Sanfeliu
- Link to profile picture (best quality you have): https://bit.ly/2sidTl6
- Job title: Android & iOS Tech Leader @ La Mobile Factory
- Company: Sopra Steria
- Twitter handle: @remysanfeliu
- Experience as a speaker:
  - [X] beginner
  - [ ] advanced
  - [ ] expert
- Links to your previous events, videos etc. : 
  - Native, crossplatform, or both ? @ Epitech, 02/2019
  - iOS Background Modes @ Meetup Swift, 17/10/2019

- Name: Julien Faixo
- Link to profile picture (best quality you have): https://github.com/jfaixo/127.0.0.1/blob/master/me.jpg
- Job title: Solution Architect
- Company: Sopra Steria
- Twitter handle: @jfaixo
- Experience as a speaker:
  - [X] beginner
  - [ ] advanced
  - [ ] expert
- Links to your previous events, videos etc. : 
  - Présentation des Interactions digitales @ Enseeiht, 2018
  - Cours sur les Interactions Digitales @ UTC1, 2018, 2019
  - Native, crossplatform, or both ? @ Epitech, 02/2019

---

## Description of your talk
Kotlin Multiplatform ❤️ Vous en avez déjà entendu parler ! Mais... En avez-vous déjà vu en production ?

Après une année de pratique, et une mise en production pour un grand client industriel, nous souhaitons vous partager notre expérience sur l'utilisation de cette technologie encore "expérimentale" pour le développement d'apps Android, iOS... mais pas que ! 😏

Au programme :
- L'application, son architecture
- Pros and Cons
- Comment économiser des semaines de refactoring
- Roadmap 2020 et nouveautés KMP
- Et si c'était à refaire ? On le refait déjà !

Soyez les `actual` de nos `expect` et rejoignez-nous pour ce talk 😄 

---

## Miscs

* Tags (e.g: angular, android, web, iot) : mobile apps, android, ios, kotlin multiplatform, industrialisation
* Talk level :
    - [ ] beginner
    - [X] advanced
    - [ ] expert
* Length (max 45 min) : 30 min
* Format:
    - [X] Slides
    - [ ] Live coding
    - [ ] Video
    - [ ] Sound
* Availability (e.g: ASAP, before/after XXX): January 2020

**Comment by remysanfeliu** [comment]
https://bit.ly/2sidTl6 :)
